# Importing Dependencies

In [1]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2

# Loading The Model

In [2]:
interpreter = tf.lite.Interpreter(model_path='singlepose-lightning.tflite')
interpreter.allocate_tensors()

# Drawing Keypoints

In [3]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 4, (0,255,0), -1) 

In [4]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

# Drawing Edges

In [5]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)

# Making Detections

In [6]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Reshape image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0), 192,192)
    input_image = tf.cast(img, dtype=tf.float32)
    
    # Setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # Make predictions 
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    
    # Rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
    cv2.imshow('MoveNet Lightning', frame)
    
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[[[0.73733795 0.5981169  0.27064577]
   [0.7122793  0.6219722  0.26748595]
   [0.71041965 0.58604836 0.26062012]
   [0.7148423  0.6827437  0.2144423 ]
   [0.70552766 0.6008994  0.21069361]
   [0.8198508  0.73428243 0.13788398]
   [0.792695   0.64230037 0.2706469 ]
   [0.8516606  0.70533884 0.05501606]
   [0.82006    0.651275   0.08437263]
   [0.825889   0.65958846 0.07888775]
   [0.7975352  0.5918062  0.09673894]
   [0.5646703  0.97801316 0.12807062]
   [0.9007496  0.6928045  0.03953436]
   [1.001127   0.6526301  0.00977663]
   [0.85547173 0.55165714 0.03182282]
   [0.99774474 0.58760405 0.01238717]
   [1.0008217  0.5212098  0.00976356]]]]
[[[[0.7305104  0.5850171  0.28887138]
   [0.7112758  0.6175079  0.20145786]
   [0.7048441  0.5784579  0.3297709 ]
   [0.7069719  0.69606847 0.19476864]
   [0.6939082  0.5840531  0.16011131]
   [0.80178213 0.73676074 0.13229024]
   [0.7589948  0.5958392  0.23569945]
   [0.8441645  0.7231225  0.08080905]
   [0.7991897  0.565318   0.13821211]
   [0.823

[[[[0.81933975 0.8426497  0.3120992 ]
   [0.77760756 0.84909457 0.26058966]
   [0.77360344 0.77665204 0.35091126]
   [0.71536416 0.78486824 0.154147  ]
   [0.719982   0.6529782  0.22102946]
   [0.77361846 0.78435874 0.16061331]
   [0.8055866  0.6188893  0.14272967]
   [0.8528689  0.8618881  0.05686569]
   [0.8511187  0.5254618  0.07091653]
   [0.8601819  0.88621604 0.04871438]
   [0.86080396 0.71198976 0.02992788]
   [0.78084934 0.72865075 0.01923086]
   [0.8252248  0.6402129  0.05766441]
   [0.84995604 0.9107305  0.01913741]
   [0.73832786 0.1768788  0.08591232]
   [0.84470475 0.91283596 0.01697719]
   [0.8481206  0.7004124  0.01450108]]]]
[[[[0.8123847  0.8415159  0.28612298]
   [0.77262616 0.8517879  0.21221246]
   [0.7693316  0.80151314 0.36053944]
   [0.72605747 0.8328774  0.16700768]
   [0.71905184 0.65190816 0.17751166]
   [0.8067566  0.8298709  0.19411786]
   [0.80693364 0.5988799  0.16383335]
   [0.8507551  0.8846065  0.09590708]
   [0.83569163 0.53952235 0.1071223 ]
   [0.845

[[[[0.8008065  0.80558074 0.2714829 ]
   [0.77008414 0.81674284 0.18317112]
   [0.76421416 0.7568538  0.29752672]
   [0.7326058  0.7857313  0.19479491]
   [0.7277865  0.64667416 0.3173618 ]
   [0.8169908  0.7895318  0.1484836 ]
   [0.81749785 0.58210105 0.20040664]
   [0.8533883  0.8399956  0.07420105]
   [0.8338739  0.53438294 0.092961  ]
   [0.84884405 0.83403486 0.09452905]
   [0.8527932  0.63451684 0.04001138]
   [0.8385955  0.7394372  0.05533614]
   [0.8499894  0.6225745  0.05530199]
   [0.8386693  0.82575536 0.02792316]
   [0.82827485 0.5302663  0.03137658]
   [0.8437149  0.8276429  0.04092101]
   [0.83186495 0.5983086  0.03629924]]]]
[[[[0.8191936  0.8282525  0.24527228]
   [0.7785107  0.8360739  0.20527941]
   [0.77426994 0.78157115 0.2579135 ]
   [0.7242591  0.78299916 0.23223709]
   [0.72090834 0.6694169  0.33993888]
   [0.79593325 0.78608847 0.18748192]
   [0.8062632  0.6039803  0.19259985]
   [0.85208297 0.87200564 0.07860018]
   [0.8369142  0.52767694 0.07022841]
   [0.849

[[[[0.7972263  0.79111546 0.22221757]
   [0.76675266 0.8093764  0.14733209]
   [0.7563983  0.7342438  0.28017217]
   [0.7256967  0.7934704  0.18830968]
   [0.7068906  0.62046087 0.16165319]
   [0.78544354 0.8139424  0.226109  ]
   [0.7810532  0.5641841  0.29245734]
   [0.85349154 0.87839115 0.11019   ]
   [0.8570542  0.5171585  0.16440207]
   [0.85063094 0.8568129  0.11659033]
   [0.85480607 0.61573476 0.04144329]
   [0.8342917  0.75354666 0.09715804]
   [0.8521301  0.6023514  0.05211371]
   [0.83615965 0.8604289  0.02998063]
   [0.8236989  0.50088966 0.02683024]
   [0.84272474 0.82252705 0.05104858]
   [0.8304965  0.60480726 0.02234212]]]]
[[[[0.78663486 0.83714885 0.34719324]
   [0.7496768  0.8350458  0.29435167]
   [0.7516197  0.7986121  0.3531223 ]
   [0.71547145 0.8002181  0.1800462 ]
   [0.71852076 0.6801111  0.30086058]
   [0.789453   0.8191478  0.24300043]
   [0.7913989  0.5805293  0.22444719]
   [0.8497579  0.86427134 0.09354287]
   [0.847257   0.5203188  0.14995976]
   [0.851

[[[[0.7859925  0.7885647  0.20349513]
   [0.7587205  0.8064439  0.15128021]
   [0.7568716  0.752753   0.35284746]
   [0.7218902  0.78197145 0.21075976]
   [0.7081219  0.62569577 0.19611274]
   [0.78849554 0.8075065  0.21430252]
   [0.78009313 0.56437665 0.28281122]
   [0.8530518  0.8824715  0.08862514]
   [0.84492695 0.53253967 0.12413895]
   [0.8541548  0.84399784 0.09847078]
   [0.84968823 0.608392   0.05542612]
   [0.85705394 0.7351979  0.07951584]
   [0.8648919  0.603783   0.07299105]
   [0.8401625  0.83943725 0.0230425 ]
   [0.8281111  0.5221035  0.03052294]
   [0.84753364 0.8155347  0.04446869]
   [0.8301946  0.62724483 0.03074078]]]]
[[[[0.7703695  0.7739622  0.16538633]
   [0.7401723  0.78897494 0.12998459]
   [0.7220818  0.65975034 0.36305827]
   [0.719367   0.7516123  0.17182307]
   [0.69908446 0.6063147  0.16742824]
   [0.8084359  0.79581684 0.18055606]
   [0.79498136 0.5487118  0.25612354]
   [0.8528239  0.8508715  0.08323943]
   [0.8562937  0.5181507  0.12107221]
   [0.849

[[[[0.8004482  0.77081054 0.22093551]
   [0.76542854 0.7912531  0.1303727 ]
   [0.7523426  0.70755064 0.2623391 ]
   [0.7373268  0.7794572  0.10709022]
   [0.7164747  0.60291076 0.16727613]
   [0.8281603  0.80955696 0.23110838]
   [0.80750954 0.54851073 0.3006322 ]
   [0.83659786 0.8953552  0.13075352]
   [0.8573858  0.5315243  0.09131537]
   [0.85815597 0.84498996 0.07508294]
   [0.86379975 0.6160464  0.03787013]
   [0.8377551  0.7143396  0.05853906]
   [0.8467602  0.5824181  0.06062812]
   [0.8374016  0.83943236 0.02987649]
   [0.83048654 0.5164685  0.02620345]
   [0.8455876  0.77769387 0.02373597]
   [0.83301234 0.54090816 0.04813969]]]]
[[[[0.76781607 0.75474954 0.3120794 ]
   [0.74587345 0.77779955 0.18364921]
   [0.73673403 0.70287246 0.26015797]
   [0.7255688  0.78757155 0.19834495]
   [0.7095741  0.62166494 0.17602412]
   [0.8131367  0.80789053 0.19241336]
   [0.78669757 0.56226736 0.25795698]
   [0.8522376  0.85863847 0.11414567]
   [0.8469541  0.52705467 0.12125563]
   [0.840

[[[[0.7744881  0.66873884 0.3325441 ]
   [0.74596345 0.71983075 0.3120772 ]
   [0.7268847  0.61800474 0.2056193 ]
   [0.7260815  0.7738351  0.20132712]
   [0.7060008  0.58769566 0.22078292]
   [0.8305289  0.810344   0.22120774]
   [0.7884752  0.5690204  0.26114205]
   [0.8464079  0.89910215 0.14590023]
   [0.84122276 0.536428   0.11494366]
   [0.85155743 0.8273329  0.10249019]
   [0.83632916 0.6068808  0.05653748]
   [0.8380697  0.74496907 0.06267603]
   [0.82838917 0.6071525  0.06787269]
   [0.83938617 0.90743566 0.05913385]
   [0.8429891  0.50871086 0.02785867]
   [0.8406376  0.8214059  0.06031842]
   [0.826856   0.49976847 0.03531279]]]]
[[[[0.7744881  0.66873884 0.3325441 ]
   [0.74596345 0.71983075 0.3120772 ]
   [0.7268847  0.61800474 0.2056193 ]
   [0.7260815  0.7738351  0.20132712]
   [0.7060008  0.58769566 0.22078292]
   [0.8305289  0.810344   0.22120774]
   [0.7884752  0.5690204  0.26114205]
   [0.8464079  0.89910215 0.14590023]
   [0.84122276 0.536428   0.11494366]
   [0.851

[[[[0.7491716  0.6534662  0.3068449 ]
   [0.7276925  0.70063233 0.26683956]
   [0.70909405 0.6215493  0.25559166]
   [0.7225289  0.72820485 0.16089463]
   [0.69618237 0.57265204 0.27034977]
   [0.8294163  0.75160897 0.19427158]
   [0.8017689  0.56291455 0.24960336]
   [0.8612744  0.80092335 0.09060162]
   [0.8436409  0.5331224  0.12558554]
   [0.85288876 0.7715912  0.06899466]
   [0.8237924  0.6037535  0.06207313]
   [0.8999683  0.7203044  0.04122815]
   [0.88965154 0.6136626  0.05243227]
   [0.8415011  0.91138434 0.07412318]
   [0.82676506 0.52479655 0.03273435]
   [0.8483617  0.82143843 0.0527835 ]
   [0.8389434  0.53041226 0.03270438]]]]
[[[[0.7619495  0.5627326  0.378543  ]
   [0.7202672  0.60661733 0.3852515 ]
   [0.7167062  0.55701506 0.32240102]
   [0.73372763 0.73172843 0.17355457]
   [0.7061998  0.5781865  0.20862094]
   [0.857151   0.80938494 0.18231793]
   [0.8203862  0.5543475  0.28555867]
   [0.8423606  0.9095797  0.15173084]
   [0.83850515 0.5488526  0.06350002]
   [0.849

[[[[0.77605593 0.6714748  0.3451725 ]
   [0.7452264  0.70032144 0.2735574 ]
   [0.7328658  0.63608956 0.22738864]
   [0.7282023  0.74539936 0.20663282]
   [0.7061433  0.5761963  0.28990805]
   [0.8368399  0.7672221  0.17143297]
   [0.8063821  0.5801653  0.20839708]
   [0.8458661  0.90671223 0.13015038]
   [0.84416056 0.53973424 0.08635032]
   [0.8531834  0.7932948  0.05365359]
   [0.8269917  0.58361876 0.05476039]
   [0.8805062  0.720736   0.04723914]
   [0.8724842  0.6082225  0.07153243]
   [0.8487332  0.9194894  0.04425697]
   [0.84044737 0.53301406 0.02399488]
   [0.8399688  0.8258628  0.03717475]
   [0.8390805  0.53292906 0.03275922]]]]
[[[[0.77605593 0.6714748  0.3451725 ]
   [0.7452264  0.70032144 0.2735574 ]
   [0.7328658  0.63608956 0.22738864]
   [0.7282023  0.74539936 0.20663282]
   [0.7061433  0.5761963  0.28990805]
   [0.8368399  0.7672221  0.17143297]
   [0.8063821  0.5801653  0.20839708]
   [0.8458661  0.90671223 0.13015038]
   [0.84416056 0.53973424 0.08635032]
   [0.853

[[[[0.7653346  0.7040664  0.31893146]
   [0.7468874  0.7340154  0.21207957]
   [0.727193   0.6443093  0.25602204]
   [0.7273985  0.75512075 0.1763864 ]
   [0.70270073 0.5696826  0.2987307 ]
   [0.81354535 0.79065824 0.16953039]
   [0.7860614  0.56213975 0.26694152]
   [0.857272   0.83490056 0.10060885]
   [0.8460431  0.5320981  0.11868379]
   [0.847556   0.8114519  0.10586987]
   [0.8379551  0.59986126 0.04748807]
   [0.8640171  0.74169654 0.08120153]
   [0.8701331  0.61019075 0.08564171]
   [0.8448359  0.82058614 0.0423005 ]
   [0.83937263 0.52880967 0.03062937]
   [0.8417155  0.823292   0.04926497]
   [0.8407618  0.5223837  0.03676497]]]]
[[[[0.7653346  0.7040664  0.31893146]
   [0.7468874  0.7340154  0.21207957]
   [0.727193   0.6443093  0.25602204]
   [0.7273985  0.75512075 0.1763864 ]
   [0.70270073 0.5696826  0.2987307 ]
   [0.81354535 0.79065824 0.16953039]
   [0.7860614  0.56213975 0.26694152]
   [0.857272   0.83490056 0.10060885]
   [0.8460431  0.5320981  0.11868379]
   [0.847

[[[[0.7667786  0.70662963 0.2748163 ]
   [0.74637103 0.73690027 0.16801602]
   [0.73023725 0.6475258  0.25282165]
   [0.7354981  0.75913227 0.13543744]
   [0.7065851  0.58666253 0.22180432]
   [0.8246645  0.77288437 0.12777503]
   [0.80437934 0.57841206 0.17804353]
   [0.8518418  0.8231544  0.06588952]
   [0.8345863  0.5369029  0.10374276]
   [0.8442677  0.8150052  0.08603098]
   [0.8254459  0.6042293  0.05109929]
   [0.8638916  0.72382903 0.05352154]
   [0.86861515 0.60965    0.06568076]
   [0.8398602  0.8222376  0.03990355]
   [0.82752025 0.5371694  0.04401461]
   [0.84046113 0.82577455 0.05121746]
   [0.8422725  0.5434184  0.03697767]]]]
[[[[0.7667786  0.70662963 0.2748163 ]
   [0.74637103 0.73690027 0.16801602]
   [0.73023725 0.6475258  0.25282165]
   [0.7354981  0.75913227 0.13543744]
   [0.7065851  0.58666253 0.22180432]
   [0.8246645  0.77288437 0.12777503]
   [0.80437934 0.57841206 0.17804353]
   [0.8518418  0.8231544  0.06588952]
   [0.8345863  0.5369029  0.10374276]
   [0.844

[[[[0.7694897  0.67122984 0.2957926 ]
   [0.7496468  0.7199995  0.29690236]
   [0.7316606  0.61810327 0.23679465]
   [0.7418441  0.74735874 0.18312357]
   [0.71566147 0.5700827  0.26879802]
   [0.83419704 0.7720276  0.17570084]
   [0.8001515  0.56459767 0.26702538]
   [0.8546549  0.8367309  0.08989834]
   [0.8412752  0.5388393  0.13375463]
   [0.85030687 0.81171125 0.08387134]
   [0.82125425 0.6010201  0.05433497]
   [0.8799902  0.74079967 0.05458645]
   [0.8644361  0.61061573 0.08434263]
   [0.84161794 0.82032514 0.04636364]
   [0.83818024 0.5433167  0.04417651]
   [0.8447882  0.8233623  0.04428696]
   [0.83763194 0.5411496  0.04236863]]]]
[[[[0.7798671  0.70288754 0.36134458]
   [0.7555078  0.7321577  0.21412541]
   [0.7402741  0.6439376  0.25345862]
   [0.7413294  0.7791985  0.12436126]
   [0.7187319  0.57389545 0.30910346]
   [0.82499576 0.8104148  0.15018445]
   [0.8079883  0.5671071  0.23119959]
   [0.85373616 0.8359966  0.07817176]
   [0.84425926 0.53687894 0.0919107 ]
   [0.841

[[[[0.7812163  0.6996655  0.37327   ]
   [0.7550311  0.7288706  0.21896599]
   [0.7360201  0.640228   0.2329002 ]
   [0.7491323  0.7751908  0.17091309]
   [0.7144866  0.5722448  0.26691014]
   [0.8490901  0.80734897 0.153257  ]
   [0.8147175  0.5531826  0.28002194]
   [0.8551167  0.83812165 0.06212507]
   [0.83801556 0.5391474  0.09500572]
   [0.8535928  0.8316932  0.08634844]
   [0.79759324 0.5836792  0.04604169]
   [0.8396021  0.72140837 0.04306609]
   [0.8489651  0.57019967 0.0630512 ]
   [0.84963316 0.9306571  0.05628475]
   [0.82831925 0.53076357 0.03561818]
   [0.8473913  0.8300583  0.05403636]
   [0.83151644 0.53972983 0.04221687]]]]
[[[[0.7713058  0.7016957  0.404457  ]
   [0.7477082  0.7319905  0.22750497]
   [0.72981715 0.6451684  0.2932029 ]
   [0.7380148  0.7749629  0.16489336]
   [0.7049768  0.5744862  0.31666994]
   [0.82343477 0.80898464 0.19425888]
   [0.80532014 0.56628096 0.27240616]
   [0.8547094  0.8376627  0.09131996]
   [0.8391926  0.537601   0.10624486]
   [0.849

[[[[0.82504845 0.7077447  0.36814442]
   [0.7896756  0.7724719  0.29379034]
   [0.7639953  0.64375854 0.27351725]
   [0.759653   0.7804097  0.14912617]
   [0.7227539  0.58750254 0.3090656 ]
   [0.85408235 0.8228435  0.1830592 ]
   [0.8297121  0.55544066 0.30471915]
   [0.83932227 0.9049656  0.07795408]
   [0.8472774  0.55219185 0.04909321]
   [0.8498711  0.86247385 0.07724124]
   [0.87232035 0.6210286  0.02316375]
   [0.848993   0.7183006  0.04201062]
   [0.8450649  0.5678688  0.0556104 ]
   [0.9910235  0.7425047  0.00518468]
   [0.85389316 0.46638438 0.01618344]
   [0.833084   0.5646342  0.0277709 ]
   [0.8304577  0.5428007  0.0470855 ]]]]
[[[[0.82504845 0.7077447  0.36814442]
   [0.7896756  0.7724719  0.29379034]
   [0.7639953  0.64375854 0.27351725]
   [0.759653   0.7804097  0.14912617]
   [0.7227539  0.58750254 0.3090656 ]
   [0.85408235 0.8228435  0.1830592 ]
   [0.8297121  0.55544066 0.30471915]
   [0.83932227 0.9049656  0.07795408]
   [0.8472774  0.55219185 0.04909321]
   [0.849

[[[[0.7708125  0.71382445 0.27224758]
   [0.75783813 0.76024044 0.16506995]
   [0.7401147  0.6766552  0.25557747]
   [0.7438349  0.7565364  0.12489685]
   [0.71616906 0.6052438  0.17252484]
   [0.8286128  0.768608   0.18776129]
   [0.82065165 0.57829654 0.209362  ]
   [0.8696632  0.8037586  0.04922602]
   [0.8311813  0.53014195 0.11309639]
   [0.85308444 0.8036618  0.09311339]
   [0.8416366  0.63542235 0.05501287]
   [0.880207   0.71750516 0.060095  ]
   [0.88530517 0.6079248  0.0618361 ]
   [0.84001327 0.8176233  0.04306626]
   [0.8243117  0.5260923  0.03785487]
   [0.8433577  0.8231473  0.05922395]
   [0.83477324 0.5250489  0.03689314]]]]
[[[[0.7708125  0.71382445 0.27224758]
   [0.75783813 0.76024044 0.16506995]
   [0.7401147  0.6766552  0.25557747]
   [0.7438349  0.7565364  0.12489685]
   [0.71616906 0.6052438  0.17252484]
   [0.8286128  0.768608   0.18776129]
   [0.82065165 0.57829654 0.209362  ]
   [0.8696632  0.8037586  0.04922602]
   [0.8311813  0.53014195 0.11309639]
   [0.853

[[[[0.7762047  0.6822598  0.31995907]
   [0.7499831  0.7110383  0.21233119]
   [0.7366843  0.6260971  0.30009153]
   [0.72846335 0.7282834  0.17611684]
   [0.70691985 0.58963215 0.32753637]
   [0.8177477  0.74741936 0.18555592]
   [0.8004782  0.56636274 0.2573197 ]
   [0.8513765  0.8439867  0.07993705]
   [0.8362678  0.53718495 0.10792274]
   [0.86185837 0.82150936 0.06151035]
   [0.8253064  0.5772114  0.04758462]
   [0.8600668  0.6995365  0.05696346]
   [0.8487047  0.5909687  0.07700521]
   [0.837994   0.8264469  0.03904341]
   [0.8287713  0.5301657  0.04362029]
   [0.84361285 0.83102125 0.04189575]
   [0.8384427  0.5249978  0.04235315]]]]
[[[[0.7945773  0.7035409  0.36781994]
   [0.76602215 0.7338354  0.1983107 ]
   [0.75189865 0.6413022  0.21200176]
   [0.741773   0.75464964 0.16500069]
   [0.7195766  0.58821577 0.26762068]
   [0.82677686 0.8026971  0.24112137]
   [0.80377096 0.5666708  0.26203611]
   [0.85841364 0.82703316 0.07884268]
   [0.84165    0.538242   0.11176153]
   [0.862

[[[[0.7772628  0.6742642  0.35395655]
   [0.75450265 0.7277237  0.23824497]
   [0.7363469  0.62191546 0.2641367 ]
   [0.74032134 0.77324295 0.15484354]
   [0.7173335  0.5882118  0.22686848]
   [0.82202435 0.80842185 0.18233514]
   [0.7959931  0.57242393 0.2526582 ]
   [0.8356702  0.8700663  0.11520871]
   [0.82722586 0.545869   0.12153822]
   [0.8485076  0.8309841  0.09208871]
   [0.82585067 0.582445   0.06595007]
   [0.8428391  0.7424516  0.06528243]
   [0.8501594  0.5927752  0.07755383]
   [0.8371637  0.8210094  0.03616908]
   [0.8374218  0.5057597  0.03711791]
   [0.84145975 0.8256561  0.05071588]
   [0.8370352  0.526317   0.04038615]]]]
[[[[0.7772628  0.6742642  0.35395655]
   [0.75450265 0.7277237  0.23824497]
   [0.7363469  0.62191546 0.2641367 ]
   [0.74032134 0.77324295 0.15484354]
   [0.7173335  0.5882118  0.22686848]
   [0.82202435 0.80842185 0.18233514]
   [0.7959931  0.57242393 0.2526582 ]
   [0.8356702  0.8700663  0.11520871]
   [0.82722586 0.545869   0.12153822]
   [0.848

[[[[0.8172576  0.73616827 0.36042833]
   [0.7706537  0.7610275  0.15085384]
   [0.75837183 0.67271984 0.2624293 ]
   [0.74362916 0.7713623  0.14297326]
   [0.7222382  0.5868692  0.2962121 ]
   [0.8511776  0.78847975 0.1723853 ]
   [0.83388233 0.55251914 0.26442745]
   [0.84245193 0.8845184  0.07520698]
   [0.84782    0.54422176 0.04579843]
   [0.84854126 0.86415815 0.09090778]
   [0.8706016  0.6209415  0.02435881]
   [0.8346104  0.6924953  0.04209753]
   [0.8314822  0.5606756  0.05584937]
   [0.84899855 0.9198251  0.0252522 ]
   [0.8574378  0.3243197  0.04300062]
   [0.8443707  0.8325429  0.0363568 ]
   [0.8301735  0.49667847 0.04382841]]]]
[[[[0.8172576  0.73616827 0.36042833]
   [0.7706537  0.7610275  0.15085384]
   [0.75837183 0.67271984 0.2624293 ]
   [0.74362916 0.7713623  0.14297326]
   [0.7222382  0.5868692  0.2962121 ]
   [0.8511776  0.78847975 0.1723853 ]
   [0.83388233 0.55251914 0.26442745]
   [0.84245193 0.8845184  0.07520698]
   [0.84782    0.54422176 0.04579843]
   [0.848

[[[[0.7702889  0.6990552  0.35144025]
   [0.7526288  0.7273898  0.26049396]
   [0.73916245 0.64199686 0.24122952]
   [0.74533266 0.7566344  0.1700206 ]
   [0.72734463 0.5998517  0.15728703]
   [0.8340222  0.78931373 0.20352808]
   [0.8077797  0.58230394 0.21273096]
   [0.8538465  0.82004535 0.09596705]
   [0.8515169  0.5345793  0.1381423 ]
   [0.8471181  0.8071823  0.1074541 ]
   [0.83317035 0.60334337 0.0619832 ]
   [0.8826219  0.74463797 0.07060074]
   [0.8879653  0.6165185  0.07435652]
   [0.8406863  0.8169148  0.05306956]
   [0.8327173  0.5238718  0.04474002]
   [0.84330523 0.8243904  0.06428284]
   [0.84320545 0.5216222  0.05719595]]]]
[[[[0.7760546  0.6229327  0.3203456 ]
   [0.74604535 0.6534336  0.3403461 ]
   [0.73841757 0.5957493  0.24595943]
   [0.7442905  0.7323092  0.17889184]
   [0.71723986 0.57784414 0.23628601]
   [0.825818   0.7875651  0.13447393]
   [0.79047835 0.5846096  0.19323665]
   [0.85044444 0.83956933 0.06840227]
   [0.815999   0.54059076 0.0985654 ]
   [0.850

[[[[0.7812923  0.67482775 0.33342713]
   [0.7550048  0.7256495  0.24295276]
   [0.7424642  0.63830805 0.23066996]
   [0.74231714 0.7519793  0.13561857]
   [0.7211742  0.57285994 0.26880455]
   [0.83856094 0.7696277  0.16059399]
   [0.8134607  0.5778787  0.13793589]
   [0.8576292  0.81813586 0.056291  ]
   [0.8376958  0.57051957 0.03448864]
   [0.8490945  0.80165446 0.06311598]
   [0.8430767  0.6094692  0.04096381]
   [0.84074223 0.7212     0.04563052]
   [0.84815305 0.60399336 0.06187078]
   [0.83843803 0.8151597  0.03863315]
   [0.826091   0.5334914  0.03138402]
   [0.837139   0.82739705 0.05517709]
   [0.82959735 0.539679   0.04032646]]]]
[[[[0.7812923  0.67482775 0.33342713]
   [0.7550048  0.7256495  0.24295276]
   [0.7424642  0.63830805 0.23066996]
   [0.74231714 0.7519793  0.13561857]
   [0.7211742  0.57285994 0.26880455]
   [0.83856094 0.7696277  0.16059399]
   [0.8134607  0.5778787  0.13793589]
   [0.8576292  0.81813586 0.056291  ]
   [0.8376958  0.57051957 0.03448864]
   [0.849

[[[[0.79351825 0.71079624 0.3160955 ]
   [0.7651036  0.75764334 0.16601808]
   [0.74729246 0.6517678  0.35295781]
   [0.74612397 0.77254057 0.14617893]
   [0.7235683  0.586243   0.2925688 ]
   [0.83481    0.790918   0.15382622]
   [0.81628287 0.56628144 0.19282076]
   [0.83732855 0.91241324 0.10719517]
   [0.8357135  0.545786   0.07994934]
   [0.8397197  0.8634986  0.10352283]
   [0.8400659  0.5930514  0.06825931]
   [0.8361356  0.7191727  0.05467705]
   [0.8505713  0.5857657  0.06991476]
   [0.83274484 0.816991   0.03304996]
   [0.8359058  0.547315   0.0290545 ]
   [0.8380096  0.8263084  0.05146243]
   [0.8367547  0.54857254 0.04878671]]]]
[[[[0.8030731  0.71061605 0.39864475]
   [0.7677525  0.76220036 0.1343313 ]
   [0.7514521  0.64592355 0.31584033]
   [0.75639266 0.7788896  0.11478796]
   [0.73602355 0.5707616  0.24163157]
   [0.8642919  0.8122341  0.16618823]
   [0.8466     0.5501034  0.260779  ]
   [0.84896207 0.91182995 0.08836311]
   [0.8506079  0.526717   0.07337202]
   [0.852

[[[[0.77787894 0.7016741  0.3122071 ]
   [0.75750923 0.7291705  0.2273673 ]
   [0.7448098  0.64688516 0.28046653]
   [0.74678177 0.75534886 0.15604973]
   [0.7286761  0.6013317  0.15220667]
   [0.8216578  0.7701394  0.1513724 ]
   [0.8115277  0.5779043  0.16987894]
   [0.8552949  0.8205182  0.07106145]
   [0.83610225 0.541383   0.11509623]
   [0.84496415 0.7990068  0.08364944]
   [0.8395246  0.6343857  0.06578565]
   [0.876421   0.7212926  0.07270501]
   [0.88170934 0.6122156  0.08214646]
   [0.84674895 0.8200221  0.05097758]
   [0.83658874 0.5465547  0.04999119]
   [0.8431926  0.8206152  0.05940247]
   [0.8393785  0.53028226 0.05586943]]]]
[[[[0.77787894 0.7016741  0.3122071 ]
   [0.75750923 0.7291705  0.2273673 ]
   [0.7448098  0.64688516 0.28046653]
   [0.74678177 0.75534886 0.15604973]
   [0.7286761  0.6013317  0.15220667]
   [0.8216578  0.7701394  0.1513724 ]
   [0.8115277  0.5779043  0.16987894]
   [0.8552949  0.8205182  0.07106145]
   [0.83610225 0.541383   0.11509623]
   [0.844

[[[[0.78794354 0.75879186 0.29258296]
   [0.7624278  0.781569   0.15412319]
   [0.74985194 0.69587004 0.28236568]
   [0.7430214  0.7740981  0.13241936]
   [0.71093696 0.5855487  0.2754384 ]
   [0.8175527  0.79108685 0.15540689]
   [0.8114549  0.5678246  0.24412206]
   [0.8524419  0.84105    0.05277235]
   [0.83773005 0.53735787 0.09141715]
   [0.84274936 0.83071303 0.09193633]
   [0.83814156 0.6113976  0.05005331]
   [0.8384802  0.73723507 0.06484509]
   [0.8508496  0.60419154 0.07153359]
   [0.83590287 0.8266668  0.03556388]
   [0.8382508  0.5415321  0.03253559]
   [0.8402769  0.8200866  0.04557935]
   [0.8358289  0.5391816  0.0492335 ]]]]
[[[[0.77810085 0.67012876 0.33014134]
   [0.753421   0.72294927 0.2704753 ]
   [0.73387265 0.61780596 0.2342919 ]
   [0.74655783 0.77070063 0.19407314]
   [0.717013   0.57819116 0.25175667]
   [0.85792005 0.80713844 0.1882224 ]
   [0.8174503  0.56824017 0.25743574]
   [0.83736765 0.9026903  0.13203388]
   [0.8392172  0.5381168  0.12863475]
   [0.849

[[[[0.7467627  0.6458899  0.31459534]
   [0.72617763 0.6735434  0.312129  ]
   [0.71270174 0.61318386 0.18049777]
   [0.7296729  0.7250048  0.16739374]
   [0.700662   0.55396247 0.2435046 ]
   [0.83502865 0.7496662  0.17410474]
   [0.80831385 0.56017476 0.1957153 ]
   [0.84460557 0.80520856 0.07078221]
   [0.83451235 0.5343967  0.08264396]
   [0.8482241  0.7733859  0.05880376]
   [0.81580776 0.6036049  0.05742854]
   [0.8824193  0.701998   0.03869339]
   [0.8695656  0.60519767 0.05803605]
   [0.8463988  0.93469995 0.07344977]
   [0.8229934  0.52547747 0.04161574]
   [0.84193844 0.820284   0.05725387]
   [0.83293116 0.52938616 0.03329977]]]]
[[[[0.7467627  0.6458899  0.31459534]
   [0.72617763 0.6735434  0.312129  ]
   [0.71270174 0.61318386 0.18049777]
   [0.7296729  0.7250048  0.16739374]
   [0.700662   0.55396247 0.2435046 ]
   [0.83502865 0.7496662  0.17410474]
   [0.80831385 0.56017476 0.1957153 ]
   [0.84460557 0.80520856 0.07078221]
   [0.83451235 0.5343967  0.08264396]
   [0.848

[[[[0.76096433 0.6244029  0.33795524]
   [0.73615146 0.654009   0.3052834 ]
   [0.7306156  0.5981931  0.25636396]
   [0.7295691  0.68862    0.23613833]
   [0.7187617  0.5708759  0.22595511]
   [0.83286065 0.7276733  0.19409177]
   [0.8108339  0.5694026  0.25189593]
   [0.85449475 0.76661336 0.05291615]
   [0.83783185 0.5515202  0.07716546]
   [0.85008925 0.7391442  0.05539308]
   [0.8217343  0.5844969  0.06390411]
   [0.8966276  0.7044503  0.04816296]
   [0.88562214 0.61612713 0.0667801 ]
   [0.83016634 0.72115725 0.04992783]
   [0.8251369  0.5336317  0.05158725]
   [0.8409728  0.8250241  0.06622612]
   [0.83820194 0.52865684 0.03744764]]]]
[[[[0.7911849  0.70313084 0.3734386 ]
   [0.7581645  0.7339494  0.17919017]
   [0.74812883 0.6430058  0.20403324]
   [0.73851156 0.7611443  0.11984305]
   [0.71703094 0.567966   0.262406  ]
   [0.8208641  0.7937047  0.14175402]
   [0.8064589  0.5647584  0.21110092]
   [0.85107064 0.8692764  0.08646868]
   [0.8418876  0.5362183  0.10669491]
   [0.848

[[[[0.7586715  0.64672303 0.28963935]
   [0.73218524 0.6755418  0.30928835]
   [0.71999574 0.60083866 0.24427399]
   [0.7306778  0.73455954 0.16246855]
   [0.70992607 0.5652642  0.17501253]
   [0.81946933 0.7554261  0.14479734]
   [0.80640626 0.56410193 0.23923843]
   [0.8423607  0.8018122  0.06230636]
   [0.83658123 0.5350473  0.11900665]
   [0.8380964  0.7923803  0.05120799]
   [0.7871911  0.58417326 0.07081152]
   [0.86455387 0.7261951  0.07088196]
   [0.8674178  0.61104965 0.08487143]
   [0.8330056  0.7142069  0.03634433]
   [0.8329252  0.5359938  0.04987175]
   [0.84316456 0.82527125 0.06407633]
   [0.8359706  0.52959156 0.03781355]]]]
[[[[0.76193535 0.66359687 0.30567428]
   [0.7358639  0.69421923 0.29086408]
   [0.7230433  0.61298656 0.18347187]
   [0.7281794  0.74989474 0.20298691]
   [0.7068156  0.58684534 0.23126404]
   [0.8362601  0.7971234  0.159531  ]
   [0.81177235 0.57661813 0.16920279]
   [0.8604578  0.82959217 0.06962464]
   [0.8451485  0.5383569  0.09948353]
   [0.854

[[[[0.75923723 0.63954616 0.27811712]
   [0.7302992  0.6737999  0.34058982]
   [0.7171531  0.57175463 0.37481713]
   [0.728711   0.734077   0.18453123]
   [0.71079296 0.57423717 0.24551241]
   [0.83916295 0.78987664 0.15744574]
   [0.82215416 0.5551666  0.28626427]
   [0.85359037 0.8271736  0.06080092]
   [0.83379126 0.53694165 0.09873454]
   [0.8343375  0.803123   0.07206082]
   [0.791631   0.56762344 0.06561443]
   [0.8814764  0.7256651  0.04832449]
   [0.8719529  0.6082243  0.06498414]
   [0.83593976 0.8278147  0.04089194]
   [0.854444   0.5101618  0.01236434]
   [0.83634377 0.82795995 0.06568816]
   [0.8372829  0.52912515 0.03894441]]]]
[[[[0.75923723 0.63954616 0.27811712]
   [0.7302992  0.6737999  0.34058982]
   [0.7171531  0.57175463 0.37481713]
   [0.728711   0.734077   0.18453123]
   [0.71079296 0.57423717 0.24551241]
   [0.83916295 0.78987664 0.15744574]
   [0.82215416 0.5551666  0.28626427]
   [0.85359037 0.8271736  0.06080092]
   [0.83379126 0.53694165 0.09873454]
   [0.834

[[[[0.7742647  0.6217005  0.31062347]
   [0.74109566 0.65611523 0.33580884]
   [0.7332394  0.5853159  0.26606342]
   [0.7391213  0.7315378  0.16381928]
   [0.7141526  0.57741594 0.2524117 ]
   [0.8354231  0.77151483 0.16049182]
   [0.7999978  0.558406   0.2522539 ]
   [0.84392375 0.9047791  0.14097604]
   [0.83611465 0.5255833  0.13694035]
   [0.8650682  0.77885175 0.05533946]
   [0.84214896 0.52165496 0.06636568]
   [0.87928617 0.708318   0.05386941]
   [0.86359537 0.5938008  0.07481109]
   [0.84921825 0.61161906 0.01898744]
   [0.84778947 0.48935252 0.02782813]
   [0.8450121  0.5377786  0.03153507]
   [0.85224557 0.3085572  0.06593317]]]]
[[[[0.7585534  0.60520124 0.30868897]
   [0.73034275 0.6495808  0.3238157 ]
   [0.7211958  0.56886625 0.300878  ]
   [0.7278444  0.69468844 0.2413844 ]
   [0.7155423  0.5700662  0.19606175]
   [0.8348269  0.75521886 0.1726844 ]
   [0.8261084  0.5654748  0.22521092]
   [0.8522102  0.7583785  0.05081713]
   [0.824826   0.5231147  0.12797894]
   [0.843

[[[[0.76273644 0.61834645 0.31569526]
   [0.73217076 0.65361154 0.34941584]
   [0.7193221  0.57119954 0.36131656]
   [0.7415855  0.73911536 0.1507944 ]
   [0.7117824  0.55941427 0.21801741]
   [0.8430507  0.7929832  0.15089282]
   [0.8088383  0.5550784  0.25216565]
   [0.85170376 0.82299984 0.07138146]
   [0.8372664  0.5268543  0.14173779]
   [0.85193944 0.80007625 0.08503056]
   [0.791209   0.5444826  0.06887555]
   [0.88246083 0.728769   0.04966783]
   [0.8702091  0.5807582  0.07206555]
   [0.8326826  0.54954964 0.03697306]
   [0.83610195 0.51017964 0.03504888]
   [0.8428511  0.54501474 0.02932643]
   [0.84078825 0.2953779  0.04984633]]]]
[[[[0.76273644 0.61834645 0.31569526]
   [0.73217076 0.65361154 0.34941584]
   [0.7193221  0.57119954 0.36131656]
   [0.7415855  0.73911536 0.1507944 ]
   [0.7117824  0.55941427 0.21801741]
   [0.8430507  0.7929832  0.15089282]
   [0.8088383  0.5550784  0.25216565]
   [0.85170376 0.82299984 0.07138146]
   [0.8372664  0.5268543  0.14173779]
   [0.851

[[[[0.7737254  0.6721165  0.3131335 ]
   [0.7550092  0.7249818  0.2634159 ]
   [0.73254436 0.618403   0.22798334]
   [0.73261905 0.7590813  0.15250759]
   [0.71347106 0.5760704  0.2629592 ]
   [0.8151765  0.8156102  0.16521111]
   [0.78379095 0.57179916 0.24522568]
   [0.83318496 0.8928188  0.173721  ]
   [0.82872576 0.5337353  0.13146676]
   [0.8442203  0.82250094 0.07065963]
   [0.81282175 0.5609326  0.07481688]
   [0.8356366  0.7625343  0.0893646 ]
   [0.8288239  0.6105852  0.07800422]
   [0.83685386 0.82950044 0.04358391]
   [0.8363041  0.52946657 0.04459508]
   [0.8335031  0.83339155 0.06174309]
   [0.83431387 0.52471745 0.05270597]]]]
[[[[0.80403924 0.7369555  0.31387347]
   [0.7722337  0.761857   0.1805142 ]
   [0.75774264 0.6747904  0.2657962 ]
   [0.74009573 0.7743304  0.13542913]
   [0.7261347  0.60342896 0.18597157]
   [0.81930035 0.80826926 0.1794285 ]
   [0.7949306  0.56502455 0.1890419 ]
   [0.83717865 0.88582695 0.14704946]
   [0.83419526 0.53556204 0.07807675]
   [0.861

[[[[0.80336845 0.71175665 0.38113227]
   [0.77736676 0.7613636  0.2049887 ]
   [0.7523843  0.649757   0.26926178]
   [0.74013126 0.79649127 0.1702072 ]
   [0.7133554  0.58698046 0.2630482 ]
   [0.80899715 0.82580745 0.20579396]
   [0.78430164 0.5647271  0.26269782]
   [0.85262537 0.9098952  0.10466633]
   [0.8442179  0.5366828  0.07579958]
   [0.84721386 0.858626   0.10622019]
   [0.8567872  0.5963479  0.0347055 ]
   [0.80790174 0.75711465 0.05537221]
   [0.7848026  0.5853299  0.06932726]
   [0.8467087  0.81840825 0.0207374 ]
   [0.8620126  0.50359416 0.00914986]
   [0.8435228  0.8254435  0.06194875]
   [0.83479017 0.52697927 0.03480514]]]]
[[[[0.7525228  0.64794683 0.2817393 ]
   [0.73368216 0.67465365 0.28109023]
   [0.7183064  0.6013279  0.26361284]
   [0.7388338  0.7326735  0.1587736 ]
   [0.70977306 0.5737471  0.20597625]
   [0.81828094 0.7547182  0.19615892]
   [0.7840032  0.5847419  0.2530117 ]
   [0.8536524  0.80311763 0.10283723]
   [0.82515067 0.57193    0.09221161]
   [0.846

[[[[0.77844596 0.71071017 0.3599654 ]
   [0.75752014 0.7616632  0.1835446 ]
   [0.7324917  0.6453558  0.2677945 ]
   [0.73115796 0.7964074  0.1861767 ]
   [0.70976967 0.572317   0.2579364 ]
   [0.81035924 0.81708956 0.16662595]
   [0.79151595 0.55568606 0.27600244]
   [0.84200215 0.8986153  0.10713454]
   [0.8345742  0.5253269  0.13041544]
   [0.8456445  0.85039663 0.1059078 ]
   [0.83299536 0.5627247  0.06218637]
   [0.81266016 0.7433466  0.06377245]
   [0.8272811  0.589296   0.0814229 ]
   [0.8375908  0.8249246  0.03473484]
   [0.8316796  0.5271143  0.03857959]
   [0.8432182  0.82988346 0.06635335]
   [0.81181186 0.52050036 0.05449982]]]]
[[[[0.76429427 0.6419391  0.31794667]
   [0.74077237 0.676165   0.27557406]
   [0.7258934  0.59759027 0.22705379]
   [0.7471231  0.7342967  0.1728173 ]
   [0.7160985  0.5766249  0.24859704]
   [0.85223377 0.78982013 0.20053425]
   [0.8266287  0.56520057 0.25101674]
   [0.8376436  0.8581655  0.10680293]
   [0.8311243  0.53802353 0.08417374]
   [0.857

[[[[0.7998787  0.7010504  0.36398652]
   [0.7602727  0.73106736 0.24660937]
   [0.7417718  0.6356653  0.22247905]
   [0.7510148  0.7867594  0.19511005]
   [0.72265184 0.6119996  0.18867198]
   [0.8609056  0.803277   0.20293263]
   [0.8270473  0.5850793  0.2317232 ]
   [0.8408438  0.88243717 0.1029829 ]
   [0.844648   0.5250575  0.08645695]
   [0.86410826 0.8077643  0.0695629 ]
   [0.84266925 0.6086684  0.0551675 ]
   [0.87866163 0.7157639  0.04643431]
   [0.8713502  0.60430735 0.05785962]
   [0.8258593  0.523374   0.02616074]
   [0.8494588  0.505172   0.01331976]
   [0.8321593  0.5664504  0.0283901 ]
   [0.85640883 0.31089932 0.05545247]]]]
[[[[0.78282064 0.73956746 0.27646714]
   [0.7580621  0.76169956 0.15546231]
   [0.7469822  0.6984266  0.32851136]
   [0.74364847 0.7573905  0.12024131]
   [0.7184462  0.5725031  0.3069028 ]
   [0.8380484  0.7678053  0.18274544]
   [0.8073262  0.5658426  0.24153592]
   [0.8568566  0.82080877 0.06706514]
   [0.83687973 0.53403515 0.09404801]
   [0.851

[[[[0.78480905 0.73286027 0.32753623]
   [0.76494545 0.77524036 0.19535892]
   [0.74939454 0.69249004 0.2976989 ]
   [0.75070786 0.7948259  0.1768296 ]
   [0.7164713  0.5890922  0.24242279]
   [0.84300107 0.80718124 0.23985298]
   [0.8288717  0.56595457 0.24297944]
   [0.85400456 0.83662057 0.08862805]
   [0.8350941  0.53487086 0.0742088 ]
   [0.8552887  0.8161213  0.10683236]
   [0.83440536 0.60972303 0.05050965]
   [0.8600224  0.73482835 0.06099851]
   [0.8520009  0.5856464  0.0584651 ]
   [0.84835976 0.91328925 0.07790817]
   [0.82308257 0.52733946 0.0283992 ]
   [0.84716964 0.82299113 0.05768054]
   [0.8327159  0.54867756 0.03540656]]]]
[[[[0.78480905 0.73286027 0.32753623]
   [0.76494545 0.77524036 0.19535892]
   [0.74939454 0.69249004 0.2976989 ]
   [0.75070786 0.7948259  0.1768296 ]
   [0.7164713  0.5890922  0.24242279]
   [0.84300107 0.80718124 0.23985298]
   [0.8288717  0.56595457 0.24297944]
   [0.85400456 0.83662057 0.08862805]
   [0.8350941  0.53487086 0.0742088 ]
   [0.855

[[[[0.7724483  0.6491317  0.34769568]
   [0.7513351  0.6961011  0.2822496 ]
   [0.73576826 0.60584545 0.35174653]
   [0.7442597  0.7281003  0.17728505]
   [0.72231054 0.5783158  0.27172077]
   [0.8430271  0.7644965  0.16908506]
   [0.81100625 0.57056177 0.2531134 ]
   [0.86801904 0.81646943 0.04612895]
   [0.8363992  0.53948873 0.11635719]
   [0.8510811  0.80016315 0.07003818]
   [0.7926942  0.58285403 0.06299758]
   [0.8800761  0.7196545  0.05410827]
   [0.8694703  0.5950587  0.07547814]
   [0.8410086  0.81458426 0.04086787]
   [0.8313312  0.5314648  0.047729  ]
   [0.8427207  0.822168   0.06229047]
   [0.8380398  0.5301713  0.03949554]]]]
[[[[0.75894374 0.66492236 0.31967288]
   [0.7410847  0.71580076 0.31432462]
   [0.71243954 0.60746425 0.30456457]
   [0.74364537 0.7712009  0.19086523]
   [0.7052843  0.5907947  0.21395053]
   [0.84419835 0.8064763  0.17632885]
   [0.78966206 0.5737498  0.24957235]
   [0.84901106 0.8410895  0.07829583]
   [0.8257854  0.5382358  0.12949793]
   [0.849

[[[[0.78361434 0.7562078  0.34270677]
   [0.75938743 0.77482593 0.21311682]
   [0.7451539  0.68351364 0.29295146]
   [0.7407529  0.7715463  0.141257  ]
   [0.72733116 0.6080506  0.25771362]
   [0.83278483 0.8040318  0.25971732]
   [0.81104827 0.5702522  0.27247423]
   [0.8547758  0.837993   0.08994921]
   [0.85292906 0.53480667 0.13660108]
   [0.8496474  0.8343613  0.11126694]
   [0.8401432  0.586254   0.09198692]
   [0.84973806 0.72118086 0.06461595]
   [0.85481095 0.58992374 0.08536664]
   [0.838446   0.8214933  0.03598125]
   [0.83773893 0.5275397  0.03782348]
   [0.8444213  0.82799745 0.04076999]
   [0.84044933 0.5405523  0.05243281]]]]
[[[[0.78361434 0.7562078  0.34270677]
   [0.75938743 0.77482593 0.21311682]
   [0.7451539  0.68351364 0.29295146]
   [0.7407529  0.7715463  0.141257  ]
   [0.72733116 0.6080506  0.25771362]
   [0.83278483 0.8040318  0.25971732]
   [0.81104827 0.5702522  0.27247423]
   [0.8547758  0.837993   0.08994921]
   [0.85292906 0.53480667 0.13660108]
   [0.849

[[[[0.7776851  0.7043847  0.3464897 ]
   [0.7559893  0.73226786 0.22408505]
   [0.73950946 0.6458461  0.30664498]
   [0.7472795  0.7697059  0.17909189]
   [0.7262057  0.60241866 0.1903149 ]
   [0.8373665  0.78689617 0.17051707]
   [0.8123009  0.5689467  0.24218462]
   [0.86455077 0.8289945  0.0471766 ]
   [0.8326303  0.5414356  0.10500751]
   [0.84975624 0.8059718  0.08495851]
   [0.83809495 0.58979607 0.07045984]
   [0.8454098  0.72016215 0.06072833]
   [0.84906626 0.59116435 0.07685884]
   [0.8307683  0.74637806 0.03609866]
   [0.82776636 0.53804106 0.05346821]
   [0.8422856  0.8208798  0.05452868]
   [0.83673954 0.545709   0.0583233 ]]]]
[[[[0.7734158  0.7140712  0.24585213]
   [0.7579895  0.7589132  0.18595698]
   [0.7443801  0.6769351  0.28886637]
   [0.7390382  0.7541613  0.12791628]
   [0.7226159  0.6055764  0.17355965]
   [0.8000192  0.76747584 0.17464371]
   [0.7782775  0.57855684 0.21291772]
   [0.850074   0.839568   0.10947404]
   [0.8333561  0.53769577 0.15647064]
   [0.849

[[[[0.78463435 0.70956844 0.35249412]
   [0.7661819  0.75707144 0.16990003]
   [0.7469203  0.6492309  0.3110371 ]
   [0.74711514 0.7760357  0.14390302]
   [0.71759856 0.5757025  0.27838194]
   [0.8396636  0.8064465  0.17152122]
   [0.80560726 0.55756307 0.25731406]
   [0.8350305  0.8902389  0.11990163]
   [0.8351853  0.53663135 0.11716335]
   [0.84380794 0.8413755  0.07120971]
   [0.8385433  0.5687417  0.07127766]
   [0.8344311  0.72085035 0.05869055]
   [0.84503174 0.5894926  0.08056886]
   [0.8322694  0.8234784  0.03866744]
   [0.83122885 0.5342054  0.04403121]
   [0.8358221  0.8331332  0.05876862]
   [0.83958316 0.5271379  0.04621825]]]]
[[[[0.78463435 0.70956844 0.35249412]
   [0.7661819  0.75707144 0.16990003]
   [0.7469203  0.6492309  0.3110371 ]
   [0.74711514 0.7760357  0.14390302]
   [0.71759856 0.5757025  0.27838194]
   [0.8396636  0.8064465  0.17152122]
   [0.80560726 0.55756307 0.25731406]
   [0.8350305  0.8902389  0.11990163]
   [0.8351853  0.53663135 0.11716335]
   [0.843

[[[[0.77815926 0.6656539  0.2859769 ]
   [0.75384974 0.72060895 0.27191615]
   [0.72994196 0.5989509  0.26466942]
   [0.7563807  0.7550086  0.11850514]
   [0.7187176  0.5780079  0.2554313 ]
   [0.8604834  0.79084295 0.14681734]
   [0.82740355 0.56618226 0.23278695]
   [0.83988345 0.905534   0.12601577]
   [0.8302839  0.54404604 0.08630865]
   [0.8495046  0.8111923  0.0713428 ]
   [0.8265237  0.57649356 0.06202311]
   [0.87838614 0.7247743  0.04887928]
   [0.86661905 0.59195054 0.068077  ]
   [0.8244715  0.72853434 0.03324891]
   [0.8269894  0.5291058  0.04906118]
   [0.8399293  0.8278877  0.06064357]
   [0.8325972  0.54577696 0.05827516]]]]
[[[[0.77554893 0.7047287  0.33941597]
   [0.7522737  0.73186916 0.20268038]
   [0.7336662  0.64596367 0.2799556 ]
   [0.7447774  0.7569505  0.13860519]
   [0.7217871  0.6001506  0.14868778]
   [0.83667076 0.7713419  0.16612358]
   [0.81253713 0.58298695 0.19345254]
   [0.85462844 0.8206614  0.06752354]
   [0.8288884  0.5450804  0.09667148]
   [0.850

[[[[0.7771768  0.649619   0.31138077]
   [0.7461004  0.67828524 0.25059947]
   [0.73379564 0.60270995 0.274416  ]
   [0.7310559  0.73534834 0.13977073]
   [0.7138201  0.58772653 0.18778934]
   [0.81359094 0.7566625  0.14794743]
   [0.801558   0.58503556 0.23139201]
   [0.8520968  0.7744044  0.04080739]
   [0.8321063  0.53940094 0.13081124]
   [0.8589439  0.7528926  0.04750204]
   [0.83901477 0.5841721  0.07019036]
   [0.8803338  0.7047291  0.05573783]
   [0.8693959  0.6109788  0.07572001]
   [0.82303154 0.5464628  0.03463012]
   [0.82414806 0.5354357  0.04331989]
   [0.82908463 0.5660335  0.0277813 ]
   [0.8294877  0.53409916 0.0412851 ]]]]
[[[[0.81395566 0.74057907 0.3165682 ]
   [0.77556026 0.7820755  0.18864864]
   [0.7620057  0.6732949  0.30250278]
   [0.7263837  0.77933455 0.17533472]
   [0.71804416 0.58531153 0.24478741]
   [0.83374643 0.8122603  0.17531224]
   [0.8078208  0.56658936 0.2381799 ]
   [0.8404643  0.9091561  0.12576358]
   [0.8469161  0.5477325  0.06364124]
   [0.840

[[[[0.7530524  0.6620833  0.25705954]
   [0.7346389  0.6878881  0.26184726]
   [0.7230062  0.61417055 0.20685075]
   [0.7363145  0.7178349  0.21630377]
   [0.7154851  0.576264   0.29964226]
   [0.8213674  0.76416314 0.21198465]
   [0.7998338  0.5782236  0.27244756]
   [0.8551747  0.8143849  0.10865111]
   [0.8407828  0.554699   0.11906705]
   [0.84912336 0.79425895 0.10794102]
   [0.8273057  0.6042917  0.08463074]
   [0.902879   0.73786396 0.07659316]
   [0.9076383  0.63492215 0.08533993]
   [0.8412317  0.8132068  0.08060795]
   [0.83726805 0.5444686  0.05588207]
   [0.8491218  0.8023302  0.05891877]
   [0.84121454 0.54880667 0.0458886 ]]]]
[[[[0.7923469  0.7014396  0.38532293]
   [0.7614732  0.73384285 0.18042645]
   [0.7356503  0.62355655 0.2855629 ]
   [0.7442806  0.77789366 0.14232275]
   [0.7161707  0.57665646 0.29529417]
   [0.8244829  0.8121226  0.15208583]
   [0.79538834 0.5678896  0.25841558]
   [0.8684112  0.8512763  0.04934022]
   [0.8359918  0.5386089  0.121143  ]
   [0.864

[[[[0.7767794  0.67149776 0.30303243]
   [0.75523376 0.7272479  0.23728278]
   [0.738202   0.6162163  0.21070349]
   [0.7455028  0.75304306 0.14571331]
   [0.7226417  0.5931379  0.23347902]
   [0.8539314  0.7895274  0.1641997 ]
   [0.8233001  0.57889515 0.21891594]
   [0.85349506 0.81926405 0.06431589]
   [0.8354308  0.5392576  0.1181151 ]
   [0.856456   0.7833886  0.05583631]
   [0.83940834 0.5707682  0.08334683]
   [0.8824997  0.7237453  0.04708364]
   [0.874365   0.60951614 0.06874786]
   [0.83909535 0.81899756 0.03807994]
   [0.8277952  0.5292583  0.04266242]
   [0.83696914 0.62421167 0.02853081]
   [0.8361015  0.5343233  0.04005434]]]]
[[[[0.7767794  0.67149776 0.30303243]
   [0.75523376 0.7272479  0.23728278]
   [0.738202   0.6162163  0.21070349]
   [0.7455028  0.75304306 0.14571331]
   [0.7226417  0.5931379  0.23347902]
   [0.8539314  0.7895274  0.1641997 ]
   [0.8233001  0.57889515 0.21891594]
   [0.85349506 0.81926405 0.06431589]
   [0.8354308  0.5392576  0.1181151 ]
   [0.856

[[[[0.7486898  0.70903873 0.24873264]
   [0.73626894 0.7313523  0.23483965]
   [0.72764677 0.6766948  0.35987   ]
   [0.73164594 0.7501258  0.20202409]
   [0.711529   0.6285678  0.20518331]
   [0.79487693 0.7729255  0.19901747]
   [0.7735843  0.6052797  0.19210204]
   [0.8291215  0.81922567 0.13081472]
   [0.8278799  0.54249114 0.20019437]
   [0.8259176  0.79397005 0.11025698]
   [0.7972523  0.6293201  0.08005251]
   [0.8381616  0.74175787 0.11734097]
   [0.84148335 0.6495389  0.11761495]
   [0.8346603  0.7772932  0.05995971]
   [0.82518125 0.69600034 0.08173286]
   [0.8455152  0.7919526  0.06242717]
   [0.8402142  0.68235457 0.03406595]]]]
[[[[0.7597704  0.64638704 0.3176732 ]
   [0.7389419  0.6771857  0.28264344]
   [0.7318586  0.60426044 0.32808423]
   [0.74422085 0.7305099  0.16469291]
   [0.7230034  0.5878619  0.23407227]
   [0.83541644 0.7494582  0.20993885]
   [0.8077899  0.5811399  0.23667194]
   [0.8543669  0.77752185 0.06225714]
   [0.83419794 0.56882465 0.07930292]
   [0.844

[[[[0.76876163 0.704689   0.27866244]
   [0.7529315  0.7304194  0.24152172]
   [0.7315879  0.6465762  0.31437546]
   [0.7448863  0.75385857 0.16733725]
   [0.71227515 0.57460976 0.3081265 ]
   [0.819168   0.76707876 0.16654326]
   [0.78846717 0.5808937  0.2210756 ]
   [0.8513911  0.82556546 0.09186826]
   [0.83543944 0.53840053 0.16703218]
   [0.8497802  0.7968075  0.08868854]
   [0.83792555 0.604384   0.07549161]
   [0.86318755 0.7160319  0.08428586]
   [0.8642868  0.6138841  0.1165189 ]
   [0.8244456  0.7423851  0.05347761]
   [0.8368043  0.54615414 0.07204362]
   [0.843289   0.82180405 0.05818243]
   [0.84155464 0.54382056 0.0607089 ]]]]
[[[[0.75582826 0.6522043  0.31685808]
   [0.7338922  0.68182623 0.3320563 ]
   [0.72284484 0.61810416 0.21169546]
   [0.7312077  0.7360999  0.17654596]
   [0.71143746 0.5683123  0.2504882 ]
   [0.8157618  0.77431226 0.1750961 ]
   [0.7976317  0.56527185 0.2859384 ]
   [0.85283124 0.8262204  0.08895113]
   [0.83286446 0.53577363 0.13487934]
   [0.845

[[[[0.76608914 0.64705896 0.3631727 ]
   [0.74479884 0.69663036 0.27821022]
   [0.73069656 0.60439163 0.31468585]
   [0.74147904 0.7516737  0.16875865]
   [0.7187741  0.57353055 0.31152424]
   [0.8411362  0.78778815 0.16177997]
   [0.80801284 0.5683715  0.24510136]
   [0.85121286 0.84189904 0.08756208]
   [0.83839107 0.53366745 0.13664088]
   [0.84872955 0.80364203 0.08837756]
   [0.82082236 0.5613467  0.07289225]
   [0.86242664 0.724547   0.05363164]
   [0.84925354 0.609372   0.06642709]
   [0.8389766  0.81924725 0.04017527]
   [0.8449337  0.50937676 0.03998067]
   [0.8421911  0.829502   0.06246353]
   [0.84008896 0.5197324  0.05019559]]]]
[[[[0.7439181  0.6002138  0.31384856]
   [0.720273   0.6466526  0.3397244 ]
   [0.71320575 0.5794623  0.24077064]
   [0.7288997  0.7211129  0.25710458]
   [0.7080304  0.57429487 0.21378097]
   [0.8265412  0.76603097 0.20584902]
   [0.8054862  0.57056963 0.24482298]
   [0.85254085 0.8213961  0.09167146]
   [0.8363168  0.5381171  0.13752244]
   [0.842

[[[[0.773704   0.6825985  0.30195352]
   [0.7525207  0.71075463 0.195921  ]
   [0.7371914  0.6250959  0.30786535]
   [0.7335478  0.714133   0.17435639]
   [0.72556293 0.57037497 0.31681046]
   [0.81555223 0.73011535 0.1730764 ]
   [0.8070229  0.56679636 0.2677163 ]
   [0.8538136  0.7874438  0.07981398]
   [0.8472537  0.54958427 0.10728078]
   [0.83963025 0.782818   0.06114423]
   [0.8259648  0.629547   0.04695502]
   [0.86452985 0.70177364 0.05978943]
   [0.8684963  0.61020756 0.07649691]
   [0.8367521  0.7480213  0.02985054]
   [0.8367865  0.5399421  0.04733701]
   [0.8427252  0.81962585 0.05235563]
   [0.84539545 0.5483912  0.03818892]]]]
[[[[0.78213614 0.6251919  0.3733298 ]
   [0.7472612  0.6765043  0.35242143]
   [0.7350359  0.58531904 0.2999319 ]
   [0.757367   0.7618181  0.12140986]
   [0.7319612  0.5533781  0.23511468]
   [0.8756325  0.7924499  0.12540619]
   [0.8463077  0.5473595  0.24176565]
   [0.8407287  0.90594    0.1078415 ]
   [0.8466109  0.53506374 0.08594678]
   [0.852

[[[[0.8001876  0.709324   0.4099702 ]
   [0.7783567  0.7754325  0.23399216]
   [0.7544892  0.64843404 0.25763348]
   [0.7607109  0.8034426  0.12405811]
   [0.72913456 0.5687705  0.34369907]
   [0.84521526 0.8348241  0.15086743]
   [0.81765556 0.5582818  0.2728467 ]
   [0.85763884 0.9070248  0.12486649]
   [0.84763426 0.5310797  0.14081188]
   [0.8580817  0.87915695 0.09404377]
   [0.8432101  0.57881826 0.07612041]
   [0.82643473 0.74286747 0.04056281]
   [0.8243582  0.5767864  0.06650396]
   [0.84253496 0.81456274 0.02885588]
   [0.82728285 0.53088355 0.04955018]
   [0.8497014  0.82871485 0.04194813]
   [0.84377587 0.5288203  0.05766239]]]]
[[[[0.8001876  0.709324   0.4099702 ]
   [0.7783567  0.7754325  0.23399216]
   [0.7544892  0.64843404 0.25763348]
   [0.7607109  0.8034426  0.12405811]
   [0.72913456 0.5687705  0.34369907]
   [0.84521526 0.8348241  0.15086743]
   [0.81765556 0.5582818  0.2728467 ]
   [0.85763884 0.9070248  0.12486649]
   [0.84763426 0.5310797  0.14081188]
   [0.858

[[[[0.75961894 0.6177718  0.35042322]
   [0.73418325 0.64940655 0.3428508 ]
   [0.7276833  0.58364093 0.26794228]
   [0.7422613  0.71079963 0.2069445 ]
   [0.7314272  0.5602443  0.25848594]
   [0.8381304  0.74948716 0.19609134]
   [0.8148203  0.55334747 0.36034942]
   [0.843516   0.7898432  0.0539803 ]
   [0.8475622  0.5281792  0.21469052]
   [0.8557891  0.7795086  0.06712597]
   [0.84303015 0.5695258  0.09299961]
   [0.89227265 0.7063879  0.06428355]
   [0.8748429  0.58165056 0.12715755]
   [0.8202592  0.64120376 0.05222742]
   [0.8426854  0.5115467  0.05801275]
   [0.8486099  0.82405686 0.05837329]
   [0.84492064 0.5448641  0.04805494]]]]
[[[[0.77374405 0.6488519  0.32074517]
   [0.74682415 0.6748092  0.31694466]
   [0.7310816  0.59318626 0.40185773]
   [0.74694276 0.72847056 0.16213848]
   [0.7235574  0.56292856 0.2891239 ]
   [0.82352084 0.7456383  0.15858175]
   [0.80488414 0.56247133 0.24208154]
   [0.84940094 0.8189656  0.05715178]
   [0.8353783  0.53561103 0.14863533]
   [0.848

[[[[0.7658784  0.7107829  0.29962346]
   [0.7468824  0.7382525  0.15133414]
   [0.7343925  0.6720698  0.27343825]
   [0.7370505  0.735388   0.0979601 ]
   [0.7180214  0.5833514  0.26493236]
   [0.8266222  0.7511468  0.17104335]
   [0.81211364 0.58014596 0.23278068]
   [0.8528898  0.79802024 0.05476323]
   [0.8470243  0.5413779  0.15751828]
   [0.84701085 0.7879864  0.06381935]
   [0.8393735  0.62414193 0.06749541]
   [0.86745685 0.6987997  0.06196156]
   [0.886538   0.6150336  0.06949009]
   [0.8288747  0.74852073 0.03525281]
   [0.82002115 0.53818226 0.06405572]
   [0.8414561  0.7662162  0.0319058 ]
   [0.83600676 0.5685848  0.04343336]]]]
[[[[0.779962   0.70599747 0.32571092]
   [0.75229084 0.7338207  0.16692038]
   [0.73911476 0.6408093  0.24414153]
   [0.74514127 0.7505263  0.131879  ]
   [0.7263297  0.56649554 0.30762273]
   [0.8482112  0.7470341  0.15429991]
   [0.8348865  0.56051683 0.27520338]
   [0.8516712  0.8185426  0.05344089]
   [0.84808004 0.5401636  0.12564217]
   [0.855

[[[[0.7564628  0.6688785  0.23614302]
   [0.7362806  0.7000911  0.22033651]
   [0.72084755 0.59064263 0.38261464]
   [0.72857183 0.75249875 0.13671325]
   [0.7163478  0.5666181  0.27659008]
   [0.79956853 0.76930165 0.14713287]
   [0.7850732  0.5664505  0.25509557]
   [0.83425546 0.85427845 0.11747271]
   [0.8225021  0.5415798  0.15263511]
   [0.8459666  0.8216661  0.09969791]
   [0.7892364  0.578842   0.08578783]
   [0.8189854  0.7392072  0.07709302]
   [0.82505786 0.60848606 0.09544642]
   [0.82189476 0.7494199  0.05381455]
   [0.83223933 0.55039227 0.07242651]
   [0.8432307  0.82945365 0.07649647]
   [0.8401331  0.54251176 0.06438129]]]]
[[[[0.7564628  0.6688785  0.23614302]
   [0.7362806  0.7000911  0.22033651]
   [0.72084755 0.59064263 0.38261464]
   [0.72857183 0.75249875 0.13671325]
   [0.7163478  0.5666181  0.27659008]
   [0.79956853 0.76930165 0.14713287]
   [0.7850732  0.5664505  0.25509557]
   [0.83425546 0.85427845 0.11747271]
   [0.8225021  0.5415798  0.15263511]
   [0.845

[[[[0.7637736  0.70197344 0.30920658]
   [0.7440123  0.73002887 0.20322688]
   [0.7292639  0.6413021  0.24603339]
   [0.7418923  0.7509851  0.14406674]
   [0.7236141  0.5739406  0.34990993]
   [0.8320023  0.74943036 0.19854896]
   [0.81984174 0.57648134 0.21937011]
   [0.85319746 0.7955524  0.07059004]
   [0.84965914 0.54266644 0.15295756]
   [0.8533267  0.79290473 0.07176447]
   [0.84674275 0.6210039  0.06686854]
   [0.88577664 0.7205001  0.05576764]
   [0.88880587 0.6135949  0.07398806]
   [0.82471156 0.7504673  0.03887425]
   [0.8344848  0.5450758  0.04831396]
   [0.84880567 0.8214997  0.03838695]
   [0.84040636 0.568132   0.04311213]]]]
[[[[0.7731142  0.7091042  0.30739713]
   [0.75080174 0.7574388  0.15615323]
   [0.7377436  0.64639044 0.28117728]
   [0.74192923 0.7554835  0.12331584]
   [0.7266927  0.56978476 0.3277735 ]
   [0.83466643 0.76837885 0.17288963]
   [0.8258228  0.56143373 0.24079591]
   [0.8387992  0.8425607  0.08399088]
   [0.8362753  0.53848904 0.1362593 ]
   [0.845

[[[[0.74737686 0.6230367  0.3386545 ]
   [0.73101664 0.6669015  0.28727153]
   [0.71296567 0.58563906 0.39312693]
   [0.72294015 0.67637503 0.24832985]
   [0.7135901  0.5702648  0.2559819 ]
   [0.8147657  0.7215452  0.21057673]
   [0.7952124  0.567893   0.28743538]
   [0.8526012  0.7624015  0.07781949]
   [0.8388556  0.5539973  0.16487111]
   [0.84969723 0.75751936 0.07350332]
   [0.8365067  0.58653975 0.10689837]
   [0.88776314 0.7004955  0.07077396]
   [0.88510203 0.6158535  0.09231491]
   [0.8255962  0.70624876 0.05496192]
   [0.8355863  0.5484054  0.06250173]
   [0.8453909  0.8111524  0.04987949]
   [0.8411913  0.57217747 0.03396799]]]]
[[[[0.7551428  0.62587804 0.36909074]
   [0.7331922  0.65314555 0.3322189 ]
   [0.727288   0.59606177 0.21611929]
   [0.73725283 0.68940306 0.16024178]
   [0.7209977  0.5665327  0.2443222 ]
   [0.817765   0.7300331  0.24230984]
   [0.8063564  0.56489617 0.29761514]
   [0.85326284 0.7734997  0.11599074]
   [0.8476102  0.5534394  0.13544849]
   [0.851

[[[[0.76933944 0.6681156  0.30295086]
   [0.74367595 0.69782823 0.2618764 ]
   [0.7295202  0.6166338  0.22946166]
   [0.7509512  0.7516755  0.17911626]
   [0.72559035 0.57586545 0.31037176]
   [0.8468818  0.7682764  0.14629   ]
   [0.8232937  0.5805811  0.25364104]
   [0.8516643  0.8207003  0.05751732]
   [0.83941334 0.55237687 0.10411127]
   [0.85511756 0.78980935 0.06104084]
   [0.7822985  0.59497255 0.07821593]
   [0.9026992  0.7230643  0.04502816]
   [0.89061135 0.61617136 0.08185904]
   [0.82594085 0.7292305  0.04129579]
   [0.83891094 0.54210883 0.05357777]
   [0.9921799  0.69897187 0.01078148]
   [0.8441383  0.5449079  0.04523879]]]]
[[[[0.76933944 0.6681156  0.30295086]
   [0.74367595 0.69782823 0.2618764 ]
   [0.7295202  0.6166338  0.22946166]
   [0.7509512  0.7516755  0.17911626]
   [0.72559035 0.57586545 0.31037176]
   [0.8468818  0.7682764  0.14629   ]
   [0.8232937  0.5805811  0.25364104]
   [0.8516643  0.8207003  0.05751732]
   [0.83941334 0.55237687 0.10411127]
   [0.855

[[[[0.8021176  0.7341735  0.29391158]
   [0.7803628  0.7774758  0.18353128]
   [0.7639324  0.69857347 0.2698622 ]
   [0.7469038  0.77560776 0.14252988]
   [0.7245029  0.5869926  0.30612212]
   [0.81814164 0.7677049  0.15166132]
   [0.8007835  0.5838919  0.2281039 ]
   [0.8396481  0.89523923 0.10499369]
   [0.82955647 0.5472063  0.12899667]
   [0.86185044 0.80963963 0.0461061 ]
   [0.84575844 0.62981695 0.0413093 ]
   [0.78771245 0.7141626  0.04021891]
   [0.80014324 0.62394553 0.07487255]
   [0.8418216  0.8219218  0.0296441 ]
   [0.8279111  0.549081   0.05132338]
   [0.8430332  0.823394   0.04691907]
   [0.8238487  0.56802446 0.05930286]]]]
[[[[0.7383074  0.6234461  0.3497286 ]
   [0.7203419  0.64803773 0.3046944 ]
   [0.71245456 0.5847723  0.31155655]
   [0.7231371  0.67908233 0.26995727]
   [0.7136675  0.5680571  0.23516029]
   [0.7998562  0.7068438  0.21788335]
   [0.78570217 0.567445   0.27366614]
   [0.8307905  0.7254533  0.08057072]
   [0.8230909  0.5518894  0.14786635]
   [0.810

[[[[0.7613852  0.649804   0.31319228]
   [0.73358965 0.6778559  0.32783148]
   [0.72456074 0.5904087  0.37495315]
   [0.72463584 0.7070786  0.19084643]
   [0.7172882  0.5704648  0.29081076]
   [0.8209393  0.747586   0.1818289 ]
   [0.80557644 0.5688649  0.2846791 ]
   [0.8565433  0.79697937 0.07485548]
   [0.8334152  0.54419833 0.14539413]
   [0.85164165 0.79411304 0.08028083]
   [0.82194185 0.5820643  0.07825942]
   [0.86390626 0.72252536 0.0691869 ]
   [0.8489871  0.6109322  0.08869418]
   [0.8328953  0.73315614 0.04155699]
   [0.8330188  0.54769176 0.05866682]
   [0.8467679  0.82244366 0.05130436]
   [0.8391678  0.54580855 0.05244724]]]]
[[[[0.7613852  0.649804   0.31319228]
   [0.73358965 0.6778559  0.32783148]
   [0.72456074 0.5904087  0.37495315]
   [0.72463584 0.7070786  0.19084643]
   [0.7172882  0.5704648  0.29081076]
   [0.8209393  0.747586   0.1818289 ]
   [0.80557644 0.5688649  0.2846791 ]
   [0.8565433  0.79697937 0.07485548]
   [0.8334152  0.54419833 0.14539413]
   [0.851

[[[[0.76329535 0.6839702  0.30670628]
   [0.73734415 0.71004385 0.20647888]
   [0.72610396 0.63392067 0.30369723]
   [0.7369167  0.7379582  0.11268427]
   [0.72016305 0.57558316 0.33620268]
   [0.8368711  0.7531812  0.17373446]
   [0.82625955 0.56368434 0.23452109]
   [0.85249674 0.7984449  0.05011386]
   [0.82858205 0.5402869  0.1022272 ]
   [0.8558351  0.79530233 0.06290597]
   [0.82191885 0.5849297  0.0626213 ]
   [0.8419189  0.70260584 0.05013802]
   [0.8466951  0.58754724 0.06351877]
   [0.8233458  0.74879044 0.03762697]
   [0.8231413  0.5389928  0.05541162]
   [0.8500947  0.82467264 0.05152566]
   [0.83703685 0.54407346 0.04823114]]]]
[[[[0.75641394 0.655434   0.31129622]
   [0.72925365 0.6817156  0.3112736 ]
   [0.7247305  0.6214268  0.22501552]
   [0.7350473  0.73753303 0.12043586]
   [0.7157032  0.5679989  0.2651827 ]
   [0.82283413 0.77440023 0.16851188]
   [0.80077016 0.5687675  0.28095666]
   [0.8535909  0.82530373 0.07969614]
   [0.838129   0.55118114 0.13233814]
   [0.854

[[[[0.7572202  0.65318966 0.3062895 ]
   [0.73722285 0.6784698  0.33784702]
   [0.7290868  0.6224096  0.27553228]
   [0.72940993 0.7262258  0.18480824]
   [0.7217033  0.57674074 0.3100615 ]
   [0.81164265 0.7495574  0.18299024]
   [0.7955986  0.5819681  0.26017618]
   [0.8527781  0.82637    0.07774579]
   [0.83808917 0.5408802  0.17179449]
   [0.8458599  0.7953105  0.07933395]
   [0.8255591  0.5822614  0.09377051]
   [0.8672937  0.72086877 0.07888353]
   [0.8657576  0.61504775 0.10731027]
   [0.8285682  0.72709984 0.04772974]
   [0.8346485  0.54396605 0.06736609]
   [0.8315105  0.64337283 0.03518686]
   [0.8390061  0.5485597  0.06673723]]]]
[[[[0.7962241  0.7852444  0.22683203]
   [0.7666607  0.7852185  0.12219881]
   [0.764435   0.74997604 0.30636176]
   [0.746186   0.74708533 0.15764987]
   [0.7329463  0.63687104 0.18447304]
   [0.84837806 0.74590003 0.15687348]
   [0.8444683  0.61556184 0.11126193]
   [0.8376398  0.8967265  0.10181508]
   [0.8373128  0.54126334 0.07504045]
   [0.861

[[[[0.75674975 0.6335169  0.35818884]
   [0.7362835  0.6759018  0.29867104]
   [0.72776663 0.60789883 0.27531084]
   [0.73245335 0.6881224  0.2350087 ]
   [0.72459096 0.58721745 0.29215643]
   [0.8308418  0.7277154  0.20959044]
   [0.8211987  0.5833318  0.24386568]
   [0.852169   0.7482704  0.06619831]
   [0.8396555  0.56838906 0.09991513]
   [0.8407075  0.7329794  0.04712059]
   [0.82705563 0.6022007  0.08775859]
   [0.8868724  0.685323   0.05904603]
   [0.8875558  0.61798024 0.07431754]
   [0.82507694 0.70758045 0.05094515]
   [0.8378581  0.5446553  0.05044051]
   [0.84791726 0.83574176 0.07161052]
   [0.8419703  0.55176365 0.05367076]]]]
[[[[0.74930227 0.627638   0.35857373]
   [0.72550976 0.65181327 0.31365392]
   [0.7150346  0.58785605 0.35565388]
   [0.7274189  0.68761194 0.25475377]
   [0.7153935  0.5702477  0.2654391 ]
   [0.82050586 0.72625136 0.20297685]
   [0.8054618  0.5567367  0.32217556]
   [0.83889025 0.74519944 0.0741786 ]
   [0.8289906  0.5392018  0.15431798]
   [0.819

[[[[0.76903105 0.70652956 0.27498862]
   [0.7480736  0.7113089  0.18234602]
   [0.7350165  0.6477504  0.31288874]
   [0.7463976  0.73181665 0.14797466]
   [0.72107214 0.5743303  0.300244  ]
   [0.8227961  0.730519   0.20011255]
   [0.8045337  0.56530654 0.2707698 ]
   [0.8513886  0.7955419  0.06817372]
   [0.838339   0.549898   0.10539803]
   [0.85028744 0.7973165  0.08142658]
   [0.8219303  0.5824881  0.08148695]
   [0.8624255  0.6972212  0.07485189]
   [0.8630295  0.59213    0.09932858]
   [0.82398385 0.73047876 0.04351692]
   [0.8258476  0.53755844 0.06698767]
   [0.84615755 0.81573606 0.05577653]
   [0.8359628  0.5475449  0.0498426 ]]]]
[[[[0.76903105 0.70652956 0.27498862]
   [0.7480736  0.7113089  0.18234602]
   [0.7350165  0.6477504  0.31288874]
   [0.7463976  0.73181665 0.14797466]
   [0.72107214 0.5743303  0.300244  ]
   [0.8227961  0.730519   0.20011255]
   [0.8045337  0.56530654 0.2707698 ]
   [0.8513886  0.7955419  0.06817372]
   [0.838339   0.549898   0.10539803]
   [0.850

[[[[0.7374582  0.6040729  0.36631647]
   [0.71775573 0.64484215 0.29440206]
   [0.7092184  0.57799506 0.23801006]
   [0.71914303 0.6827092  0.26892826]
   [0.6953473  0.5550133  0.2438426 ]
   [0.80767775 0.7462617  0.16142529]
   [0.7832367  0.5584481  0.2904622 ]
   [0.82575727 0.7934343  0.07491536]
   [0.821102   0.5351362  0.18067557]
   [0.8395039  0.78283393 0.06990048]
   [0.7808466  0.55155486 0.10649728]
   [0.86672086 0.7242745  0.08006082]
   [0.8664272  0.60914594 0.12380295]
   [0.81583893 0.7277934  0.07059138]
   [0.8367552  0.5081017  0.07472138]
   [0.84521234 0.81986415 0.07350086]
   [0.8408042  0.5244236  0.06568433]]]]
[[[[0.7699368  0.6793489  0.27524623]
   [0.73901415 0.68537915 0.25763342]
   [0.7319592  0.62202    0.23847662]
   [0.72945714 0.7134479  0.14454156]
   [0.71895427 0.58581805 0.23514529]
   [0.8326809  0.746819   0.14421439]
   [0.8182027  0.56546414 0.23301747]
   [0.84222835 0.8985785  0.10472398]
   [0.83184755 0.5395085  0.10695385]
   [0.847

[[[[0.75375736 0.62842643 0.38252354]
   [0.7350584  0.67319715 0.33464   ]
   [0.71816075 0.58914435 0.35104144]
   [0.7314428  0.7322046  0.18679854]
   [0.71312356 0.5675535  0.25548524]
   [0.80143046 0.77174485 0.15016949]
   [0.78404474 0.57043666 0.30777055]
   [0.83603567 0.8237943  0.08943962]
   [0.82043374 0.53970206 0.19120005]
   [0.84100354 0.779201   0.09035006]
   [0.8199579  0.5494558  0.0959154 ]
   [0.843327   0.7257158  0.09913336]
   [0.8434314  0.611116   0.13966823]
   [0.82197475 0.7271937  0.05855971]
   [0.8281288  0.53487885 0.06236894]
   [0.8374054  0.8033079  0.07447025]
   [0.8363638  0.5323779  0.06419505]]]]
[[[[0.75375736 0.62842643 0.38252354]
   [0.7350584  0.67319715 0.33464   ]
   [0.71816075 0.58914435 0.35104144]
   [0.7314428  0.7322046  0.18679854]
   [0.71312356 0.5675535  0.25548524]
   [0.80143046 0.77174485 0.15016949]
   [0.78404474 0.57043666 0.30777055]
   [0.83603567 0.8237943  0.08943962]
   [0.82043374 0.53970206 0.19120005]
   [0.841

[[[[0.753627   0.62525946 0.32507446]
   [0.73304814 0.67132914 0.2554188 ]
   [0.7251143  0.61489844 0.16786268]
   [0.7422847  0.73197865 0.15419713]
   [0.71752656 0.58612007 0.22068956]
   [0.8332557  0.7487449  0.16798794]
   [0.8043353  0.6005542  0.18468222]
   [0.85310316 0.76762176 0.07419999]
   [0.8284426  0.5389817  0.15734003]
   [0.8432014  0.7653246  0.04829258]
   [0.8225588  0.62796533 0.06779564]
   [0.88115585 0.72027016 0.06324025]
   [0.8830492  0.6316134  0.0823449 ]
   [0.8235003  0.5536293  0.07450604]
   [0.8246116  0.53927135 0.08402071]
   [0.8495569  0.81583375 0.06949017]
   [0.8391523  0.53535485 0.066453  ]]]]
[[[[0.753627   0.62525946 0.32507446]
   [0.73304814 0.67132914 0.2554188 ]
   [0.7251143  0.61489844 0.16786268]
   [0.7422847  0.73197865 0.15419713]
   [0.71752656 0.58612007 0.22068956]
   [0.8332557  0.7487449  0.16798794]
   [0.8043353  0.6005542  0.18468222]
   [0.85310316 0.76762176 0.07419999]
   [0.8284426  0.5389817  0.15734003]
   [0.843

[[[[0.7526495  0.62259114 0.36637947]
   [0.7307075  0.64938897 0.3159097 ]
   [0.722545   0.5841366  0.35842726]
   [0.72909564 0.68211675 0.29281813]
   [0.7208759  0.57031673 0.28582144]
   [0.8177604  0.7273337  0.2264899 ]
   [0.8016752  0.56930935 0.31981987]
   [0.8543832  0.74364257 0.06316058]
   [0.842457   0.5503049  0.14799494]
   [0.8522973  0.7284218  0.0600395 ]
   [0.8246926  0.58084106 0.10671271]
   [0.8920083  0.7023783  0.06917455]
   [0.8897971  0.6160114  0.09481003]
   [0.82807267 0.6397953  0.0575862 ]
   [0.83861053 0.53643376 0.06723677]
   [0.83559966 0.6442321  0.03366755]
   [0.8467412  0.5455817  0.04118069]]]]
[[[[0.7526495  0.62259114 0.36637947]
   [0.7307075  0.64938897 0.3159097 ]
   [0.722545   0.5841366  0.35842726]
   [0.72909564 0.68211675 0.29281813]
   [0.7208759  0.57031673 0.28582144]
   [0.8177604  0.7273337  0.2264899 ]
   [0.8016752  0.56930935 0.31981987]
   [0.8543832  0.74364257 0.06316058]
   [0.842457   0.5503049  0.14799494]
   [0.852

[[[[0.7589547  0.6471241  0.3270787 ]
   [0.73681563 0.6765429  0.31317103]
   [0.72744656 0.59446406 0.38084924]
   [0.74059665 0.7328185  0.14392251]
   [0.7194737  0.57390964 0.31183386]
   [0.83018744 0.7687437  0.12140071]
   [0.8061075  0.5702266  0.27712923]
   [0.8419489  0.8228583  0.07092129]
   [0.82343805 0.5516666  0.12301273]
   [0.83980584 0.8013498  0.06874374]
   [0.79536384 0.5842835  0.10128443]
   [0.86636555 0.7246231  0.06674874]
   [0.86569715 0.5966017  0.10891402]
   [0.8198471  0.72933745 0.05167422]
   [0.83163834 0.5378108  0.06933713]
   [0.8446983  0.8244003  0.06697521]
   [0.83840597 0.5326328  0.06149281]]]]
[[[[0.7380642  0.62448126 0.3411205 ]
   [0.71993494 0.64833355 0.2897344 ]
   [0.7135161  0.5875228  0.3339179 ]
   [0.7225527  0.68073577 0.23963054]
   [0.7147052  0.5714382  0.23913318]
   [0.80102336 0.71308464 0.21094258]
   [0.78954476 0.5709559  0.28543845]
   [0.8388655  0.7551305  0.07156844]
   [0.82805216 0.5492999  0.12880744]
   [0.817

[[[[0.7710947  0.646017   0.38514102]
   [0.742602   0.6929126  0.31804174]
   [0.7324368  0.6119617  0.25124115]
   [0.7396035  0.76707923 0.22789568]
   [0.7157821  0.5912837  0.22376163]
   [0.84253025 0.8022787  0.17247804]
   [0.7986497  0.5717535  0.2818582 ]
   [0.8703739  0.8208555  0.06499837]
   [0.8481467  0.54131526 0.17534526]
   [0.87404436 0.78816295 0.098722  ]
   [0.8589592  0.5493985  0.07413783]
   [0.88850373 0.7308589  0.06923861]
   [0.8684198  0.5726802  0.12453161]
   [0.8417236  0.55064654 0.05581607]
   [0.86412466 0.4448713  0.03374727]
   [0.8519039  0.49796867 0.04692728]
   [0.8779115  0.37782234 0.0366911 ]]]]
[[[[0.7710947  0.646017   0.38514102]
   [0.742602   0.6929126  0.31804174]
   [0.7324368  0.6119617  0.25124115]
   [0.7396035  0.76707923 0.22789568]
   [0.7157821  0.5912837  0.22376163]
   [0.84253025 0.8022787  0.17247804]
   [0.7986497  0.5717535  0.2818582 ]
   [0.8703739  0.8208555  0.06499837]
   [0.8481467  0.54131526 0.17534526]
   [0.874

[[[[0.7693133  0.64352196 0.33372107]
   [0.7422625  0.6738508  0.32685816]
   [0.73595405 0.60694265 0.28776792]
   [0.7489519  0.7468524  0.24784754]
   [0.7359991  0.57866025 0.30276355]
   [0.831566   0.77877486 0.14921938]
   [0.80365694 0.56843144 0.29447573]
   [0.8432435  0.90172064 0.1729844 ]
   [0.84771264 0.5365046  0.21265139]
   [0.85954916 0.83752716 0.09456966]
   [0.8493271  0.5275632  0.09098495]
   [0.8393931  0.7327878  0.08917297]
   [0.843254   0.59206337 0.12228878]
   [0.8243937  0.74900234 0.05791147]
   [0.8458292  0.50416774 0.09513846]
   [0.8580231  0.7933139  0.04892292]
   [0.8499576  0.5365     0.05853762]]]]
[[[[0.76894635 0.6425899  0.30623195]
   [0.73781437 0.68765354 0.31248376]
   [0.7313751  0.6010628  0.37350446]
   [0.7475964  0.77311414 0.22312704]
   [0.73097193 0.57429725 0.23862877]
   [0.8508262  0.830347   0.12560338]
   [0.821224   0.5607527  0.29421932]
   [0.84101313 0.9080373  0.12502591]
   [0.8397931  0.5399107  0.18302518]
   [0.857

[[[[0.74539924 0.64009595 0.3125718 ]
   [0.7194493  0.66806716 0.37335578]
   [0.7127399  0.6058718  0.3296132 ]
   [0.72824997 0.7292713  0.29958636]
   [0.71393794 0.58732396 0.26967642]
   [0.8322253  0.77065104 0.251833  ]
   [0.7970699  0.579661   0.36491612]
   [0.85570073 0.7959973  0.13140436]
   [0.8391141  0.54987276 0.27562466]
   [0.85765    0.79302764 0.12850435]
   [0.83488584 0.5864645  0.10491753]
   [0.8866384  0.7456862  0.10089464]
   [0.8735801  0.6171817  0.13644722]
   [0.82623047 0.7477671  0.07624196]
   [0.8398032  0.5492887  0.07507678]
   [0.8549905  0.8276001  0.08594706]
   [0.8558418  0.5446271  0.0452535 ]]]]
[[[[0.7668144  0.65140617 0.409638  ]
   [0.7412194  0.6959151  0.35783523]
   [0.7245958  0.6027121  0.47531176]
   [0.74585146 0.7559494  0.23666865]
   [0.7181214  0.57368153 0.30020905]
   [0.8453521  0.7876403  0.15329738]
   [0.80664694 0.5627331  0.30377904]
   [0.853243   0.8387703  0.07210644]
   [0.8397045  0.5329308  0.20546907]
   [0.858

[[[[0.76318496 0.6482389  0.37299722]
   [0.737904   0.69595116 0.34910995]
   [0.7252097  0.59946203 0.4632978 ]
   [0.74609435 0.7697689  0.27555472]
   [0.72001135 0.5866368  0.29164404]
   [0.8410547  0.7859496  0.2061692 ]
   [0.80089235 0.5729492  0.31358418]
   [0.8577944  0.82469666 0.10419069]
   [0.8438856  0.5405574  0.25329664]
   [0.8612765  0.7964004  0.09991954]
   [0.8284825  0.5722019  0.08228473]
   [0.86684954 0.7302239  0.08376588]
   [0.86504936 0.59839356 0.12941092]
   [0.8260092  0.6738195  0.04973403]
   [0.8438338  0.50319743 0.08941346]
   [0.8503563  0.6062139  0.03073199]
   [0.85171956 0.49426872 0.05377647]]]]
[[[[0.76286143 0.6471864  0.3970408 ]
   [0.7349567  0.6948292  0.31677118]
   [0.72027063 0.60354406 0.43223295]
   [0.7521992  0.797487   0.23836212]
   [0.71868914 0.5862419  0.18868963]
   [0.86426014 0.82948303 0.1923232 ]
   [0.81609434 0.5721553  0.339893  ]
   [0.85983324 0.8951072  0.09250445]
   [0.84980035 0.5439061  0.22761005]
   [0.862

[[[[0.75747913 0.73957205 0.47322264]
   [0.7081759  0.7691819  0.26758033]
   [0.68932    0.7012665  0.36686718]
   [0.6975385  0.75372267 0.3283091 ]
   [0.6754145  0.57657623 0.40193546]
   [0.8612745  0.8038963  0.30313212]
   [0.8328334  0.44013774 0.34411627]
   [0.9627673  0.90281284 0.03737973]
   [0.85546875 0.3159316  0.1381649 ]
   [0.86924136 0.90373397 0.10175049]
   [0.8703987  0.52676165 0.04233783]
   [0.8398869  0.6553209  0.02970183]
   [0.8908237  0.35278457 0.06113655]
   [0.85239756 0.9109994  0.02429893]
   [0.85717833 0.30692923 0.05208251]
   [0.86707175 0.93452287 0.01773331]
   [0.84020174 0.2856911  0.04911646]]]]
[[[[0.72811294 0.7033862  0.40915373]
   [0.6745316  0.75089586 0.6492797 ]
   [0.662454   0.64851415 0.4852953 ]
   [0.70997924 0.7735549  0.51244307]
   [0.6829917  0.5373777  0.6989244 ]
   [0.87403435 0.8260473  0.33234802]
   [0.81687677 0.4326311  0.43078488]
   [0.964509   0.91899    0.01543137]
   [0.9303832  0.33167678 0.01765219]
   [0.865

[[[[0.7012595  0.653108   0.6446818 ]
   [0.6363073  0.7009567  0.6955123 ]
   [0.64443576 0.5886657  0.5412394 ]
   [0.6650398  0.74229497 0.50231314]
   [0.67446935 0.5057978  0.70443135]
   [0.8542026  0.79889536 0.419584  ]
   [0.81724703 0.3687542  0.6169261 ]
   [0.966232   0.8907897  0.03251071]
   [0.9356799  0.30630338 0.02452713]
   [0.86665934 0.8070928  0.03234629]
   [0.9595539  0.47271368 0.01009987]
   [0.7415056  0.6864857  0.0232271 ]
   [0.99943775 0.45604956 0.01817395]
   [0.9731447  0.9710263  0.02061927]
   [0.8329543  0.4067924  0.00911664]
   [0.8291053  1.0112002  0.0138318 ]
   [0.37848777 0.9785425  0.03171816]]]]
[[[[0.6964586  0.64207983 0.60612947]
   [0.6353549  0.69517726 0.75568926]
   [0.64194095 0.5815989  0.47683394]
   [0.6723246  0.7436731  0.5326775 ]
   [0.67646426 0.5017628  0.63379705]
   [0.86743546 0.8018569  0.35590062]
   [0.83211863 0.37489364 0.44702613]
   [0.96033335 0.8723926  0.02002043]
   [0.93657845 0.30710626 0.01841746]
   [0.874

[[[[0.71796906 0.5467479  0.62378836]
   [0.63780165 0.60508096 0.42558146]
   [0.6398164  0.47999924 0.5867188 ]
   [0.6675271  0.6505378  0.5181803 ]
   [0.6749425  0.38996935 0.6785368 ]
   [0.87555045 0.7053597  0.23146406]
   [0.83690894 0.28650314 0.32286614]
   [0.93928945 0.78778243 0.01050238]
   [0.96416986 0.03061693 0.03630888]
   [0.85201955 0.7714082  0.02271577]
   [0.97029513 0.39105818 0.00416923]
   [0.73055995 0.6082171  0.00784531]
   [0.583343   0.34148628 0.01586304]
   [0.87200105 0.85386205 0.00613881]
   [0.83646655 0.13729955 0.02669604]
   [0.6636375  0.7080492  0.01262262]
   [0.80180657 0.11922719 0.01387976]]]]
[[[[0.71796906 0.5467479  0.62378836]
   [0.63780165 0.60508096 0.42558146]
   [0.6398164  0.47999924 0.5867188 ]
   [0.6675271  0.6505378  0.5181803 ]
   [0.6749425  0.38996935 0.6785368 ]
   [0.87555045 0.7053597  0.23146406]
   [0.83690894 0.28650314 0.32286614]
   [0.93928945 0.78778243 0.01050238]
   [0.96416986 0.03061693 0.03630888]
   [0.852

[[[[0.72282875 0.5346756  0.7010548 ]
   [0.6468765  0.5930238  0.6701789 ]
   [0.648533   0.46639502 0.595278  ]
   [0.67897815 0.63913864 0.58109915]
   [0.6798707  0.3748499  0.57812095]
   [0.8744695  0.68792224 0.18206687]
   [0.8450169  0.26141313 0.3246583 ]
   [0.9334732  0.7658434  0.00815086]
   [0.966149   0.02938587 0.03868135]
   [0.84055895 0.7368455  0.01794176]
   [0.9718367  0.32609832 0.00553602]
   [0.7841486  0.520405   0.01548035]
   [0.5877367  0.31978112 0.00920626]
   [0.3941029  0.99524736 0.0454355 ]
   [0.8441257  0.1336031  0.02782457]
   [0.3869046  0.9888682  0.03703246]
   [0.38757348 0.9759106  0.03192018]]]]
[[[[0.7212876  0.53138757 0.70643246]
   [0.6454088  0.5919806  0.6471221 ]
   [0.6476798  0.46166503 0.50750554]
   [0.67872804 0.6419474  0.51039803]
   [0.6814984  0.37184188 0.61408615]
   [0.8736119  0.6893493  0.14785251]
   [0.8398099  0.27959216 0.2600074 ]
   [0.9316384  0.74616945 0.0068196 ]
   [0.9654915  0.02928688 0.032822  ]
   [0.688

[[[[0.7060503  0.5110916  0.69723415]
   [0.6292984  0.56369257 0.5616087 ]
   [0.63856554 0.4389993  0.6709557 ]
   [0.66176194 0.60911304 0.56773156]
   [0.6833233  0.35565847 0.533751  ]
   [0.8805086  0.6858275  0.38439915]
   [0.8585882  0.23855446 0.40020886]
   [0.9525725  0.7870207  0.01638027]
   [0.9637012  0.02659169 0.0444718 ]
   [0.8635976  0.7290372  0.01977682]
   [0.35157353 0.9804668  0.0784467 ]
   [0.4026088  0.9800433  0.05488942]
   [0.4005757  0.9808357  0.05602065]
   [0.40590012 0.9843875  0.05617813]
   [0.859935   0.14242217 0.02425899]
   [0.84564346 0.8118281  0.00479885]
   [0.403956   0.9850787  0.03470835]]]]
[[[[0.7060503  0.5110916  0.69723415]
   [0.6292984  0.56369257 0.5616087 ]
   [0.63856554 0.4389993  0.6709557 ]
   [0.66176194 0.60911304 0.56773156]
   [0.6833233  0.35565847 0.533751  ]
   [0.8805086  0.6858275  0.38439915]
   [0.8585882  0.23855446 0.40020886]
   [0.9525725  0.7870207  0.01638027]
   [0.9637012  0.02659169 0.0444718 ]
   [0.863

[[[[0.7027914  0.46413207 0.6494048 ]
   [0.63069594 0.5333855  0.51209456]
   [0.6344764  0.4013667  0.45712367]
   [0.6722922  0.6110116  0.63766587]
   [0.6731672  0.34611985 0.65350986]
   [0.87578505 0.6694832  0.37047246]
   [0.842528   0.24084705 0.48674622]
   [0.9468807  0.78068435 0.01688262]
   [0.9626953  0.02320525 0.04811864]
   [0.8548493  0.6230604  0.00752463]
   [0.9540197  0.30757865 0.00628364]
   [0.73990035 0.49939275 0.01258906]
   [0.5908184  0.30959147 0.01669604]
   [1.0261239  0.72872704 0.00702192]
   [0.8444747  0.14180769 0.01360465]
   [0.6612238  0.65061367 0.01917348]
   [0.81448334 0.00878617 0.01494518]]]]
[[[[0.71572185 0.46445724 0.59319067]
   [0.6385478  0.535197   0.565706  ]
   [0.6394235  0.40200847 0.48923853]
   [0.67340887 0.6150595  0.6346887 ]
   [0.6704678  0.35314628 0.5458144 ]
   [0.87455046 0.67259496 0.32417583]
   [0.83868253 0.23929423 0.4572924 ]
   [0.93594855 0.78135693 0.01293584]
   [0.96313953 0.02340139 0.04777391]
   [0.355

[[[[0.71839035 0.4769026  0.5313734 ]
   [0.6417486  0.5471455  0.4759367 ]
   [0.64098835 0.41246063 0.4176128 ]
   [0.67852485 0.618876   0.5361396 ]
   [0.6766144  0.35304245 0.61208475]
   [0.87663126 0.66695786 0.2670036 ]
   [0.85451293 0.23090625 0.3419318 ]
   [0.9337281  0.7613058  0.01065006]
   [0.96528506 0.02568038 0.03909722]
   [0.81938577 0.6076473  0.01208889]
   [0.97529626 0.3024746  0.00531845]
   [0.73209035 0.50876755 0.00753832]
   [0.6028994  0.2921293  0.0161095 ]
   [1.0234947  0.7520856  0.00669544]
   [0.8499624  0.142988   0.01656819]
   [0.74185264 0.509203   0.00535868]
   [0.8055551  0.10302794 0.00738769]]]]
[[[[0.7146115  0.4799919  0.48256558]
   [0.6408264  0.54746747 0.4464127 ]
   [0.63982385 0.41498142 0.41364977]
   [0.6800393  0.61738414 0.5021783 ]
   [0.67847216 0.35293636 0.6443604 ]
   [0.8846566  0.6700444  0.19966425]
   [0.85734737 0.246836   0.2639433 ]
   [0.93459463 0.76164484 0.00935787]
   [0.9649481  0.02721795 0.03747014]
   [0.817

[[[[0.6748097  0.5472065  0.6306708 ]
   [0.60846627 0.60133475 0.6068679 ]
   [0.6134398  0.47604153 0.58760214]
   [0.6516814  0.6439953  0.55718255]
   [0.6633175  0.3844026  0.60262007]
   [0.9004164  0.72550344 0.2814251 ]
   [0.8605215  0.25939903 0.47964242]
   [0.9552805  0.8064601  0.01435749]
   [0.9647379  0.02800408 0.04009812]
   [0.86806434 0.77131104 0.02515654]
   [0.9610057  0.34971154 0.01048123]
   [0.3835114  0.9889258  0.05125007]
   [0.38314065 0.979896   0.05817293]
   [0.8640432  0.909253   0.0066758 ]
   [0.38452905 0.97602165 0.06361205]
   [0.3898307  0.9844543  0.04798945]
   [0.39857    0.9835498  0.04261955]]]]
[[[[0.6748097  0.5472065  0.6306708 ]
   [0.60846627 0.60133475 0.6068679 ]
   [0.6134398  0.47604153 0.58760214]
   [0.6516814  0.6439953  0.55718255]
   [0.6633175  0.3844026  0.60262007]
   [0.9004164  0.72550344 0.2814251 ]
   [0.8605215  0.25939903 0.47964242]
   [0.9552805  0.8064601  0.01435749]
   [0.9647379  0.02800408 0.04009812]
   [0.868

[[[[0.6411911  0.57671285 0.37593606]
   [0.595801   0.6128216  0.38711163]
   [0.5966725  0.53789353 0.4310447 ]
   [0.62938863 0.6521175  0.36536378]
   [0.6264852  0.47011942 0.3869541 ]
   [0.8235726  0.69003147 0.30499122]
   [0.83794606 0.38854074 0.30651304]
   [0.8521587  0.757761   0.06089856]
   [0.87612265 0.4019189  0.02516846]
   [0.7402803  0.67855394 0.08243867]
   [0.7688183  0.51520276 0.03137938]
   [0.995387   0.64997363 0.05679151]
   [0.99197143 0.45155108 0.03602899]
   [0.850876   0.75714326 0.03629993]
   [0.85496044 0.43677986 0.02595252]
   [0.8491943  0.71641934 0.01777023]
   [0.8541435  0.54863226 0.01531689]]]]
[[[[0.6411911  0.57671285 0.37593606]
   [0.595801   0.6128216  0.38711163]
   [0.5966725  0.53789353 0.4310447 ]
   [0.62938863 0.6521175  0.36536378]
   [0.6264852  0.47011942 0.3869541 ]
   [0.8235726  0.69003147 0.30499122]
   [0.83794606 0.38854074 0.30651304]
   [0.8521587  0.757761   0.06089856]
   [0.87612265 0.4019189  0.02516846]
   [0.740

[[[[0.4569802  0.5991354  0.69692534]
   [0.3728369  0.6622283  0.5718262 ]
   [0.36185157 0.52317727 0.7364352 ]
   [0.40690205 0.6911644  0.41722527]
   [0.39413226 0.4090285  0.637573  ]
   [0.6941001  0.7901151  0.7574586 ]
   [0.6395828  0.23107594 0.55773216]
   [0.9503514  0.89477813 0.03135642]
   [0.85320586 0.11065011 0.13141233]
   [0.8579456  0.8108158  0.00444695]
   [0.76898324 0.3549518  0.00775834]
   [0.48209986 0.51255405 0.00944406]
   [0.92787695 0.26009932 0.01000202]
   [0.65935946 0.8438275  0.01305438]
   [0.70922345 0.16511129 0.03112827]
   [0.6070024  1.024205   0.00520268]
   [0.69943595 0.03098508 0.026576  ]]]]
[[[[0.44461736 0.60767806 0.70103633]
   [0.36176965 0.6627407  0.6234788 ]
   [0.35703385 0.53330195 0.689358  ]
   [0.39234245 0.6872329  0.4116452 ]
   [0.3821646  0.40958226 0.7442812 ]
   [0.6857641  0.7911283  0.7573106 ]
   [0.6356653  0.23184106 0.46001792]
   [0.88702786 0.8712203  0.02132239]
   [0.83810014 0.11187963 0.08216362]
   [0.578

[[[[0.40809163 0.6161257  0.785259  ]
   [0.32359648 0.67669594 0.78312135]
   [0.3188614  0.5381663  0.75264174]
   [0.3524359  0.70445    0.43954706]
   [0.34557498 0.42127067 0.7124431 ]
   [0.65312356 0.8090775  0.55219805]
   [0.62095153 0.23095691 0.46294853]
   [0.87182236 0.8715669  0.01641497]
   [0.8632509  0.11338504 0.0976479 ]
   [0.8584511  0.88054293 0.00885125]
   [0.72229624 0.33359405 0.01274414]
   [0.44507903 0.53851855 0.01303423]
   [0.88607687 0.05232069 0.02589383]
   [0.67227143 0.9550903  0.00718829]
   [0.66426176 0.16964416 0.0417444 ]
   [0.5639148  1.0228562  0.00583391]
   [0.75996274 0.02391378 0.02489621]]]]
[[[[0.42032787 0.6231043  0.5364947 ]
   [0.33602497 0.6803229  0.7196294 ]
   [0.32579556 0.54339206 0.621075  ]
   [0.3631539  0.70303    0.56227887]
   [0.35467935 0.42063087 0.6674957 ]
   [0.6650787  0.80982935 0.667642  ]
   [0.6541916  0.21215862 0.43167353]
   [0.8945062  0.88764733 0.01717091]
   [0.881439   0.12541723 0.04537084]
   [0.858

[[[[0.45157298 0.61624384 0.8193333 ]
   [0.3625545  0.6845466  0.77125806]
   [0.3559452  0.5361812  0.7321133 ]
   [0.38289762 0.7219161  0.6394944 ]
   [0.38411054 0.4234091  0.8121571 ]
   [0.6778356  0.8118543  0.80587727]
   [0.61160386 0.24284153 0.8240439 ]
   [0.91873574 0.9026012  0.01428978]
   [0.860022   0.10560121 0.24218592]
   [0.88217545 0.984116   0.01766481]
   [0.8665246  0.11642681 0.10813857]
   [0.4856885  0.56209433 0.01346881]
   [0.98833174 0.28876016 0.01620102]
   [0.74688995 0.95977634 0.00593885]
   [0.60101223 0.24893665 0.01817954]
   [0.65358037 1.0241112  0.00427226]
   [0.86953896 0.14385964 0.01924147]]]]
[[[[0.45692345 0.61498517 0.8125074 ]
   [0.36451542 0.68510985 0.76879174]
   [0.35369605 0.5403194  0.70452   ]
   [0.38356695 0.72149795 0.63645935]
   [0.37684965 0.42428634 0.69243324]
   [0.6859052  0.81489605 0.78171134]
   [0.62323487 0.22881928 0.7439264 ]
   [0.9256844  0.9090549  0.01054902]
   [0.86312294 0.10821906 0.2138522 ]
   [0.879

[[[[0.44524166 0.5953537  0.7522732 ]
   [0.3597924  0.6600418  0.7958266 ]
   [0.35300583 0.5191544  0.666759  ]
   [0.38668925 0.69794077 0.67021286]
   [0.38245723 0.4064008  0.744209  ]
   [0.6765206  0.79522526 0.6694797 ]
   [0.6253316  0.21961257 0.64698195]
   [0.9280925  0.9100417  0.01014009]
   [0.8700882  0.09994923 0.21344903]
   [0.85805625 0.9942304  0.01110601]
   [0.8767929  0.21937947 0.06291884]
   [0.4642646  0.5043573  0.01486339]
   [0.9937164  0.28908238 0.0211879 ]
   [0.65146977 0.9574952  0.00895629]
   [0.81865853 0.3102373  0.01572814]
   [0.5254088  1.0001853  0.01055576]
   [0.86133325 0.25442457 0.01878841]]]]
[[[[0.44524166 0.5953537  0.7522732 ]
   [0.3597924  0.6600418  0.7958266 ]
   [0.35300583 0.5191544  0.666759  ]
   [0.38668925 0.69794077 0.67021286]
   [0.38245723 0.4064008  0.744209  ]
   [0.6765206  0.79522526 0.6694797 ]
   [0.6253316  0.21961257 0.64698195]
   [0.9280925  0.9100417  0.01014009]
   [0.8700882  0.09994923 0.21344903]
   [0.858

[[[[0.45244035 0.5192657  0.57807136]
   [0.36603636 0.57754564 0.7028655 ]
   [0.36654246 0.44204134 0.8051715 ]
   [0.39031488 0.6093619  0.5109987 ]
   [0.39989457 0.33355016 0.6518631 ]
   [0.6232202  0.7325574  0.8144689 ]
   [0.6243387  0.1809064  0.78406084]
   [0.893181   0.8242714  0.22094591]
   [0.8889384  0.04347043 0.11183117]
   [0.88539904 0.8963573  0.07265975]
   [0.86296165 0.2102128  0.02075452]
   [0.4913661  0.49163342 0.01975103]
   [0.9878501  0.24215022 0.01298489]
   [0.87807864 0.79795855 0.01227244]
   [0.62488323 0.17885682 0.01898241]
   [0.735003   1.0031426  0.006555  ]
   [0.72106856 0.02362973 0.02176843]]]]
[[[[0.44261095 0.5098514  0.6548296 ]
   [0.35510787 0.56753176 0.70914805]
   [0.3596283  0.4321084  0.59916985]
   [0.38185188 0.60477936 0.58716744]
   [0.39816827 0.32856023 0.667115  ]
   [0.6296055  0.7281424  0.78973174]
   [0.62526935 0.17574458 0.78557825]
   [0.8845569  0.7951064  0.1244935 ]
   [0.89533687 0.03042629 0.11413489]
   [0.878

[[[[0.43407866 0.48616016 0.68014514]
   [0.35584924 0.53691214 0.5687306 ]
   [0.36186787 0.40708232 0.8656763 ]
   [0.38164353 0.5762065  0.5303164 ]
   [0.40030143 0.3071893  0.78757405]
   [0.63227665 0.7050721  0.77384114]
   [0.6233505  0.1627265  0.79574263]
   [0.88312805 0.80826896 0.11673817]
   [0.89111936 0.02280507 0.15644985]
   [0.86830014 0.88938594 0.06606411]
   [0.87029165 0.19616407 0.01435555]
   [0.37527844 0.67148155 0.01590826]
   [0.24854343 0.2557924  0.02588106]
   [0.8643533  0.87097704 0.00974681]
   [0.6218512  0.15581343 0.02576001]
   [0.7364652  0.886045   0.00215433]
   [0.74616826 0.02006562 0.0157622 ]]]]
[[[[0.44204396 0.4874382  0.67809063]
   [0.3602376  0.5388874  0.67564225]
   [0.36567804 0.4082954  0.8270235 ]
   [0.3820271  0.5766512  0.52711   ]
   [0.39981663 0.30447325 0.7944167 ]
   [0.6164149  0.7027194  0.68813246]
   [0.6269244  0.1604359  0.809413  ]
   [0.8793428  0.83452797 0.2037099 ]
   [0.89680195 0.02267559 0.09371814]
   [0.861